/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.ClassicalLimit.Age

/-!
# Examples: the age of top-free charts and its special cases

Roadmap, the section "The top-free witnesses: the finite age and its classical limit", step 1 and
the hereditary half of step 2, with their special cases.

* **The empty chart.**  The chart on no points is empty; it is the only top-free chart on no
  points; its only substructure is `⊥`, and every top-free chart isomorphic to that substructure is
  the empty chart.  The hull language has no constant symbols, so the empty substructure is allowed.
* **The one-point chart.**  `TopFreeIndex.point` is the one-point scheme with the bottom label.
  Its substructures are `⊥` and `⊤`, isomorphic to top-free charts on no points and on one point.
  A stage type with a cell labelled `⊤` is not top-free.  The library has no legal one-point stage
  type with a label other than `⊥`, so this is stated for an arbitrary stage type.
* **Repeated coordinates.**  In a top-free chart no relation holds of a tuple with a repeated
  point, and a hull operation with equal arguments takes its default value, the first argument.
* **A pair that is not closed.**  In a top-free chart, the substructure generated by two points
  that do not form a closed face is isomorphic to a top-free chart on more than two points: the
  generated substructure is the hull.  The library has no legal stage type on three or more
  points, so this is stated for an arbitrary top-free chart.
* **Literal restrictions.**  The top-free chart isomorphic to a substructure is the literal
  restriction of the stage type to the closed face of its points, whose labels are those of the
  visible cells (`StageType.comap_label`); in particular distinct cells sharing a graded index keep
  their own labels.
* **Closure under reindexing and restriction** (semantic contract, item 12).
* **The base stage `ω`.**  The index is countable, the age is hereditary and nonempty, and it has
  countably many isomorphism types.
* **The stage `0`.**  At stage `0` a stage type is top-free exactly when every label is `⊥`, and
  step 1 holds there as well.
-/

universe u

namespace VaughtConjecture

open FirstOrder Language Structure Finset CategoryTheory
open scoped Ordinal

variable {α : Ordinal.{u}}

/-- A structure with no points is isomorphic only to top-free charts on no points. -/
private theorem arity_eq_zero_of_equiv {M : Type*} [(hullLanguage.{u} α).Structure M] [IsEmpty M]
    {i : TopFreeIndex.{u} α} (e : M ≃[hullLanguage.{u} α] topFreeChart α i) : i.1 = 0 :=
  Nat.eq_zero_of_not_pos fun h ↦ IsEmpty.false (e.symm (Fin.mk 0 h : Fin i.1))

/-! ### The empty chart -/

/-- The empty chart has no points. -/
private example : IsEmpty (topFreeChart α (TopFreeIndex.empty α)) :=
  inferInstanceAs (IsEmpty (Fin 0))

/-- The only top-free index on no points is the empty chart: there is only one stage type on no
points (`StageType.eq_of_zero`). -/
private theorem eq_empty_of_arity_eq_zero (i : TopFreeIndex.{u} α) (hi : i.1 = 0) :
    i = TopFreeIndex.empty α := by
  rcases i with ⟨_ | k, P, hP⟩
  · exact Sigma.ext rfl (heq_of_eq (Subtype.ext (StageType.eq_of_zero _ _)))
  · exact absurd hi (Nat.succ_ne_zero k)

/-- The only substructure of the empty chart is `⊥`, and every top-free chart isomorphic to it is
the empty chart. -/
private example (S : (hullLanguage.{u} α).Substructure (topFreeChart α (TopFreeIndex.empty α))) :
    S = ⊥ ∧ ∀ j : TopFreeIndex.{u} α,
      Nonempty (S ≃[hullLanguage.{u} α] topFreeChart α j) → j = TopFreeIndex.empty α := by
  have : IsEmpty S := ⟨fun x ↦ Fin.elim0 x.1⟩
  exact ⟨SetLike.ext fun x ↦ Fin.elim0 x,
    fun j ⟨e⟩ ↦ eq_empty_of_arity_eq_zero j (arity_eq_zero_of_equiv e)⟩

/-! ### The one-point chart -/

/-- The one-point chart is the one-point stage type with the bottom label. -/
private example : (TopFreeIndex.point α).1 = 1 ∧ ∀ d, (TopFreeIndex.point α).2.1.label d = ⊥ :=
  ⟨rfl, fun _ ↦ rfl⟩

/-- A stage type with a cell labelled `⊤` is not top-free. -/
private example {n : ℕ} (t : StageType.{u} α n) (d : Fin t.card) (h : t.label d = ⊤) :
    ¬ t.IsTopFree :=
  fun ht ↦ ht d h

/-- The one-point chart has one point. -/
private theorem subsingleton_point : Subsingleton (topFreeChart α (TopFreeIndex.point α)) :=
  inferInstanceAs (Subsingleton (Fin 1))

/-- No point of the one-point chart is in its substructure `⊥`: the hull language has no constant
symbols. -/
private theorem notMem_bot_point (x : Fin (TopFreeIndex.point α).1) :
    (TopFreeIndex.point α).2.1.toChart x ∉
      (⊥ : (hullLanguage.{u} α).Substructure (topFreeChart α (TopFreeIndex.point α))) := by
  have h := (StageType.toChart_mem_closure_iff (TopFreeIndex.point α).2.2.1 ∅ x).not.mpr (by
    rw [Geometry.hull_eq_self (TopFreeIndex.point α).2.1.isPlan.empty_mem (empty_subset _)]
    exact notMem_empty x)
  rwa [coe_empty, Set.image_empty, Substructure.closure_empty] at h

/-- The substructures of the one-point chart are `⊥` and `⊤`, isomorphic to top-free charts on no
points and on one point. -/
private example :
    (∀ S : (hullLanguage.{u} α).Substructure (topFreeChart α (TopFreeIndex.point α)),
      S = ⊥ ∨ S = ⊤) ∧
    (∀ j : TopFreeIndex.{u} α, Nonempty ((⊥ : (hullLanguage.{u} α).Substructure
      (topFreeChart α (TopFreeIndex.point α))) ≃[hullLanguage.{u} α] topFreeChart α j) →
        j = TopFreeIndex.empty α) ∧
    (∀ j : TopFreeIndex.{u} α, Nonempty ((⊤ : (hullLanguage.{u} α).Substructure
      (topFreeChart α (TopFreeIndex.point α))) ≃[hullLanguage.{u} α] topFreeChart α j) →
        j.1 = 1) := by
  have := subsingleton_point (α := α)
  set x₀ : topFreeChart α (TopFreeIndex.point α) := (TopFreeIndex.point α).2.1.toChart ⟨0, one_pos⟩
  refine ⟨fun S ↦ ?_, fun j ⟨e⟩ ↦ ?_, fun j ⟨e⟩ ↦ ?_⟩
  · by_cases h : x₀ ∈ S
    · refine Or.inr (eq_top_iff.mpr fun x _ ↦ ?_)
      rwa [Subsingleton.elim x x₀]
    · refine Or.inl (eq_bot_iff.mpr fun x hx ↦ (h ?_).elim)
      rwa [Subsingleton.elim x x₀] at hx
  · have : IsEmpty (⊥ : (hullLanguage.{u} α).Substructure
        (topFreeChart α (TopFreeIndex.point α))) :=
      ⟨fun x ↦ notMem_bot_point x.1 x.2⟩
    exact eq_empty_of_arity_eq_zero j (arity_eq_zero_of_equiv e)
  · exact Fin.equiv_iff_eq.mp ⟨(Substructure.topEquiv.comp e.symm).toEquiv⟩

/-! ### Repeated coordinates -/

/-- In a top-free chart no relation holds of a tuple with a repeated point. -/
private example (i : TopFreeIndex.{u} α) {n : ℕ} (p : StageType.{u} α n) (hp : p.IsLegal)
    (xs : Fin n → topFreeChart α i) (j j' : Fin n) (hjj : j ≠ j') (h : xs j = xs j') :
    ¬ RelMap (hullLanguage.rel p hp) xs :=
  fun ⟨hinj, _⟩ ↦ hjj (hinj h)

/-- In a top-free chart a hull operation with equal arguments takes its default value. -/
private example (i : TopFreeIndex.{u} α) (ι : HullIndex.{u} α) (x : topFreeChart α i) :
    funMap (hullLanguage.op ι) ![x, x] = x :=
  Realization.hullOp_self (R := i.2.1.faceRealization) ι x

/-! ### A pair that is not closed -/

/-- In a top-free chart, the substructure generated by two points that do not form a closed face
is isomorphic to a top-free chart on more than two points: the generated substructure is the hull
(`StageType.toChart_mem_closure_iff`), which contains a third point. -/
private example (i : TopFreeIndex.{u} α) {a b : Fin i.1}
    (hab : ({a, b} : Finset (Fin i.1)) ∉ i.2.1.toCellScheme.faces) :
    ∃ j : TopFreeIndex.{u} α, 2 < j.1 ∧
      Nonempty (Substructure.closure (hullLanguage.{u} α)
        (i.2.1.toChart '' ({a, b} : Finset (Fin i.1)) : Set (topFreeChart α i))
          ≃[hullLanguage.{u} α] topFreeChart α j) := by
  have hne : Geometry.hull univ i.2.1.toCellScheme.faces {a, b} ≠ {a, b} :=
    fun h ↦ hab (i.2.1.isPlan.isConvexGeometry.hull_eq_self_iff.mp h)
  obtain ⟨x, hx, hxab⟩ := exists_of_ssubset
    (Finset.ssubset_iff_subset_ne.mpr ⟨Geometry.subset_hull (subset_univ _), hne.symm⟩)
  have hab' : a ≠ b := by
    rintro rfl
    exact hab (by simpa using i.2.1.isPlan.singleton_mem (mem_univ a))
  have hsub := Geometry.subset_hull (S := ({a, b} : Finset (Fin i.1)))
    (P := i.2.1.toCellScheme.faces) (subset_univ _)
  obtain ⟨j, ⟨e⟩⟩ := exists_equiv_topFreeChart i _ Substructure.FG.of_finite
  refine ⟨j, ?_, ⟨e⟩⟩
  -- the hull, which has at least the three points `a`, `b`, `x`, is the image of the points of `j`
  have hH : Geometry.hull univ i.2.1.toCellScheme.faces {a, b} ⊆
      univ.image fun k : Fin j.1 ↦ i.2.1.toChart.symm (e.symm k).1 := fun y hy ↦ by
    obtain ⟨k, hk⟩ := e.symm.toEquiv.surjective
      ⟨i.2.1.toChart y, (StageType.toChart_mem_closure_iff i.2.2.1 _ y).mpr hy⟩
    refine mem_image.mpr ⟨k, mem_univ _, ?_⟩
    change i.2.1.toChart.symm (e.symm.toEquiv k).1 = y
    rw [hk]
    rfl
  have h3 : #(insert x ({a, b} : Finset (Fin i.1))) = 3 := by
    rw [card_insert_of_notMem hxab, card_pair hab']
  have := (card_le_card (insert_subset hx hsub)).trans ((card_le_card hH).trans card_image_le)
  rw [h3, card_univ, Fintype.card_fin] at this
  omega

/-! ### Literal restrictions -/

/-- The top-free chart isomorphic to a substructure is the literal restriction of the stage type to
the closed face of its points, with the labels of the visible cells. -/
private example (i : TopFreeIndex.{u} α)
    (S : (hullLanguage.{u} α).Substructure (topFreeChart α i)) :
    ∃ (m : ℕ) (g : Fin m ↪ Fin i.1) (hg : univ.map g ∈ i.2.1.toCellScheme.faces),
      (∀ x, i.2.1.toChart x ∈ S ↔ x ∈ univ.map g) ∧
      Nonempty (S ≃[hullLanguage.{u} α]
        topFreeChart α ⟨m, i.2.1.comap g hg, i.2.2.1.comap g hg, i.2.2.2.comap hg⟩) ∧
      ∀ c, (i.2.1.comap g hg).label c = i.2.1.label (i.2.1.cellMap g c) := by
  obtain ⟨m, g, hg, hS, he⟩ := StageType.exists_equiv_comap i.2.2.1 S
  exact ⟨m, g, hg, hS, he, fun _ ↦ rfl⟩

/-- The age of a top-free chart lies in the age of top-free charts. -/
private example (i : TopFreeIndex.{u} α) :
    (hullLanguage.{u} α).age (topFreeChart α i) ⊆ topFreeAge α :=
  hereditary_topFreeAge _ (topFreeChart_mem_topFreeAge i)

/-! ### Closure under reindexing and restriction -/

/-- Legal top-free stage types are closed under reindexing and restriction to closed faces. -/
private example (i : TopFreeIndex.{u} α) {m : ℕ} (e : Fin m ≃ Fin i.1) (f : Fin m ↪ Fin i.1)
    {q : StageType.{u} α m} (hq : StageType.restrictFace f i.2.1 = some q) :
    ((i.2.1.reindex e).IsLegal ∧ (i.2.1.reindex e).IsTopFree) ∧ (q.IsLegal ∧ q.IsTopFree) :=
  ⟨⟨i.2.2.1.reindex e, i.2.2.2.reindex e⟩, i.2.2.1.restrictFace f hq, i.2.2.2.restrictFace hq⟩

/-! ### The base stage -/

/-- At `ω` the index is countable and every top-free chart is countable. -/
private example : Countable (TopFreeIndex.{u} ω) ∧ ∀ i, Countable (topFreeChart ω i) :=
  ⟨inferInstance, fun _ ↦ inferInstance⟩

/-- At `ω` the age of top-free charts is nonempty and hereditary, its members are finitely
generated, and it has countably many isomorphism types. -/
private example : (topFreeAge.{u} ω).Nonempty ∧ Hereditary (topFreeAge.{u} ω) ∧
    (∀ M ∈ topFreeAge.{u} ω, Structure.FG (hullLanguage.{u} ω) M) ∧
    (Quotient.mk' '' topFreeAge.{u} ω).Countable :=
  ⟨nonempty_topFreeAge, hereditary_topFreeAge, fun _ ↦ fg_of_mem_topFreeAge,
    countable_quotient_topFreeAge (Set.countable_coe_iff.mp countable_Iio_omega0_coe)⟩

/-! ### The stage `0` -/

/-- At stage `0` a stage type is top-free exactly when every label is `⊥`. -/
private example {n : ℕ} (t : StageType.{u} 0 n) : t.IsTopFree ↔ ∀ d, t.label d = ⊥ :=
  ⟨fun ht d ↦ (Label.atStage_zero_iff.mp (t.atStage d)).resolve_right (ht d),
    fun h d hd ↦ bot_ne_top ((h d).symm.trans hd)⟩

/-- At stage `0` the index is countable and the age is hereditary with countably many isomorphism
types. -/
private example : Countable (TopFreeIndex.{u} 0) ∧ Hereditary (topFreeAge.{u} 0) ∧
    (Quotient.mk' '' topFreeAge.{u} 0).Countable := by
  have h : (Set.Iio (0 : Ordinal.{u})).Countable := by simp
  exact ⟨countable_topFreeIndex h, hereditary_topFreeAge, countable_quotient_topFreeAge h⟩

end VaughtConjecture
