/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.ClassicalLimit.Amalgamation

/-!
# Examples: amalgamation and joint embedding of top-free charts, and their special cases

Roadmap, the section "The top-free witnesses: the finite age and its classical limit", step 2
(amalgamation and joint embedding, under the coatom extension property), with its special cases.
Every statement of amalgamation or joint embedding below assumes the coatom extension property
`StageType.HasCoatomExtensions`, which is not proved (roadmap, Layer 3, 3.1, (R6)).

* **Capping.**  A stage type whose labels are at most the cap is its own capped stage type; a cell
  labelled `⊤` carries the cap after capping; the one-point chart is its own capped stage type.
* **Stage `0`.**  There is no ordinal cap below stage `0`; there every top-free label is `⊥`
  (`VaughtConjecture.ClassicalLimit.AgeExamples`) and capping at `⊥` is lawful and changes no
  top-free label, so the hypothesis `0 < α` is a restriction of the ordinal-valued cap, not of
  amalgamation.
* **The empty chart.**  The embedding of the empty chart into a top-free chart is unique, so the
  square over the empty chart commutes for any two embeddings.
* **Two one-point charts over the empty chart.**  Under the coatom extension property, their
  amalgam over the empty chart, which is their joint embedding, is a top-free chart with at least
  one point.
* **A common chart equal to one of the two.**  Under the coatom extension property, amalgamation
  along the identity embedding gives an embedding `a` with `a = b.comp g`.
* **Equal charts with equal embeddings.**  Under the coatom extension property, an embedding is
  amalgamated with itself.
* **A common chart generated by two of its points.**  If the hull of two points of a top-free chart
  is all of its points and it has more than two points, then under the coatom extension property
  its amalgam has more than two points, and any two embeddings of it into the amalgam that agree
  at the two points are equal (`StageType.eq_of_restrictFace_eq_some`).  The library has no legal
  stage type on three or more points, so this is stated for an arbitrary top-free chart.
* **The base stage `ω`.**  At `ω` the hypotheses on the stage hold, and under the coatom extension
  property the age is a Fraïssé class with a Fraïssé limit.
-/

universe u

namespace VaughtConjecture

open FirstOrder Language Structure Finset Label CategoryTheory
open scoped Ordinal

variable {α : Ordinal.{u}}

/-! ### Capping -/

/-- A stage type whose labels are at most the cap is its own capped stage type. -/
private theorem cap_eq_self {n : ℕ} (t : StageType.{u} α n) {c : Ordinal.{u}}
    (hc : IsSelfVisible n (c : Label)) (hcα : c < α) (htc : ∀ d, t.label d ≤ c) :
    t.cap c hc hcα = t :=
  Option.some_injective _ ((StageType.restrictFace_refl _).symm.trans
    (StageType.restrictFace_cap (StageType.restrictFace_refl t) htc))

/-- A cell labelled `⊤` carries the cap after capping. -/
private example {n : ℕ} (t : StageType.{u} α n) {c : Ordinal.{u}}
    (hc : IsSelfVisible n (c : Label)) (hcα : c < α) (d : Fin t.card) (hd : t.label d = ⊤) :
    (t.cap c hc hcα).label d = c := by
  rw [StageType.cap_label, hd, min_eq_right le_top]

/-- The one-point chart is its own capped stage type, for every cap: its label is `⊥`. -/
private example {c : Ordinal.{u}} (hc : IsSelfVisible 1 (c : Label)) (hcα : c < α) :
    (TopFreeIndex.point α).2.1.cap c hc hcα = (TopFreeIndex.point α).2.1 :=
  cap_eq_self _ hc hcα fun _ ↦ bot_le

/-! ### Stage `0` -/

/-- At stage `0` there is no ordinal cap, but capping a top-free stage type at `⊥` is lawful and
changes none of its labels: they are all `⊥`. -/
private example {n : ℕ} (t : StageType.{u} 0 n) (ht : t.IsTopFree) :
    (∀ c : Ordinal.{u}, ¬ c < 0) ∧ t.rows.IsLawful (fun d ↦ min (t.label d) ⊥) ∧
      ∀ d, min (t.label d) ⊥ = t.label d := by
  refine ⟨fun _ ↦ not_lt.mpr zero_le,
    t.isLawful.min_const_of_isSelfVisible t.grade_le (isSelfVisible_bot n), fun d ↦ ?_⟩
  rw [(Label.atStage_zero_iff.mp (t.atStage d)).resolve_right (ht d), min_self]

/-! ### The empty chart -/

/-- The embedding of the empty chart into a top-free chart is unique, so the square over the empty
chart commutes for any two embeddings. -/
private example (i j : TopFreeIndex.{u} α)
    (f g : topFreeChart α (TopFreeIndex.empty α) ↪[hullLanguage.{u} α] topFreeChart α j) :
    f = g ∧ Nonempty (topFreeChart α (TopFreeIndex.empty α) ↪[hullLanguage.{u} α]
      topFreeChart α i) :=
  ⟨Embedding.ext fun x ↦ Fin.elim0 x,
    ⟨StageType.chartEmbedding (i.restrictFace_empty Function.Embedding.ofIsEmpty)⟩⟩

/-! ### Two one-point charts over the empty chart -/

/-- The embedding of the empty chart into the one-point chart. -/
private noncomputable def emptyPoint :
    topFreeChart α (TopFreeIndex.empty α) ↪[hullLanguage.{u} α]
      topFreeChart α (TopFreeIndex.point α) :=
  StageType.chartEmbedding ((TopFreeIndex.point α).restrictFace_empty Function.Embedding.ofIsEmpty)

/-- **Amalgamation over the empty chart of two one-point charts**, under the coatom extension
property, which is assumed here (it is compiled, `StageType.hasCoatomExtensions`): the two copies of
the one-point chart are amalgamated over
the empty chart, in a top-free chart with at least one point. -/
private example (hext : StageType.HasCoatomExtensions.{u} α) (hα : Order.IsSuccPrelimit α)
    (h0 : 0 < α) :
    ∃ (l : TopFreeIndex.{u} α)
      (a b : topFreeChart α (TopFreeIndex.point α) ↪[hullLanguage.{u} α] topFreeChart α l),
        a.comp emptyPoint = b.comp emptyPoint ∧ 1 ≤ l.1 := by
  obtain ⟨l, a, b, hab⟩ := exists_amalgam_topFreeChart hext hα h0 _ _ _ emptyPoint emptyPoint
  refine ⟨l, a, b, hab, ?_⟩
  let e : Fin 1 ↪ Fin l.1 := ⟨fun x ↦ a x, a.injective⟩
  simpa using Fintype.card_le_of_embedding e

/-- **Joint embedding of the one-point chart with itself**, under the coatom extension property,
which is assumed here (it is compiled, `StageType.hasCoatomExtensions`). -/
private example (hext : StageType.HasCoatomExtensions.{u} α) (hα : Order.IsSuccPrelimit α)
    (h0 : 0 < α) :
    ∃ l : TopFreeIndex.{u} α,
      Nonempty (topFreeChart α (TopFreeIndex.point α) ↪[hullLanguage.{u} α] topFreeChart α l) :=
  (exists_jointEmbedding_topFreeChart hext hα h0 _ (TopFreeIndex.point α)).imp fun _ h ↦ h.1

/-! ### Special configurations of the common chart -/

/-- **A common chart equal to one of the two charts**, under the coatom extension property, which is
assumed here (it is compiled, `StageType.hasCoatomExtensions`): amalgamating the identity embedding
of a top-free chart with an embedding
`g` gives an embedding `a` of the chart with `a = b.comp g`. -/
private example (hext : StageType.HasCoatomExtensions.{u} α) (hα : Order.IsSuccPrelimit α)
    (h0 : 0 < α) (i k : TopFreeIndex.{u} α)
    (g : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α k) :
    ∃ (l : TopFreeIndex.{u} α) (a : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α l)
      (b : topFreeChart α k ↪[hullLanguage.{u} α] topFreeChart α l), a = b.comp g := by
  obtain ⟨l, a, b, hab⟩ := exists_amalgam_topFreeChart hext hα h0 i i k
    (Embedding.refl (hullLanguage.{u} α) _) g
  exact ⟨l, a, b, by rwa [Embedding.comp_refl] at hab⟩

/-- **Equal charts with equal embeddings**, under the coatom extension property, which is assumed
here (it is compiled, `StageType.hasCoatomExtensions`): an embedding of top-free charts is
amalgamated with itself. -/
private example (hext : StageType.HasCoatomExtensions.{u} α) (hα : Order.IsSuccPrelimit α)
    (h0 : 0 < α) (i j : TopFreeIndex.{u} α)
    (f : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α j) :
    ∃ (l : TopFreeIndex.{u} α) (a b : topFreeChart α j ↪[hullLanguage.{u} α] topFreeChart α l),
      a.comp f = b.comp f :=
  exists_amalgam_topFreeChart hext hα h0 i j j f f

/-- Two embeddings of a top-free chart generated by two of its points (the hull of the two points
is all of its points) that agree at the two points are equal: both are chart embeddings of face
maps along which the restriction is the chart (`StageType.exists_eq_chartEmbedding`), and these face
maps agree by the two-charts theorem (`StageType.eq_of_restrictFace_eq_some`). -/
private theorem eq_of_apply_eq_of_hull_eq_univ {i l : TopFreeIndex.{u} α} {x₀ x₁ : Fin i.1}
    (hgen : Geometry.hull univ i.2.1.toCellScheme.faces {x₀, x₁} = univ)
    (φ ψ : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α l)
    (h₀ : φ (i.2.1.toChart x₀) = ψ (i.2.1.toChart x₀))
    (h₁ : φ (i.2.1.toChart x₁) = ψ (i.2.1.toChart x₁)) : φ = ψ := by
  obtain ⟨e, he, rfl⟩ := StageType.exists_eq_chartEmbedding (P := i.2.1) (Q := l.2.1)
    (.inl i.2.2.1) φ
  obtain ⟨e', he', rfl⟩ := StageType.exists_eq_chartEmbedding (P := i.2.1) (Q := l.2.1)
    (.inl i.2.2.1) ψ
  simp only [StageType.chartEmbedding_toChart] at h₀ h₁
  obtain rfl := StageType.eq_of_restrictFace_eq_some hgen he he' (l.2.1.toChart.injective h₀)
    (l.2.1.toChart.injective h₁)
  rfl

/-- **A common chart generated by two of its points, with more than two points**, under the coatom
extension property, which is assumed here (it is compiled, `StageType.hasCoatomExtensions`): the
amalgam has more than two points, and any
two embeddings of the common chart into the amalgam that agree at the two points are equal. -/
private example (hext : StageType.HasCoatomExtensions.{u} α) (hα : Order.IsSuccPrelimit α)
    (h0 : 0 < α) (i j k : TopFreeIndex.{u} α) {x₀ x₁ : Fin i.1}
    (hgen : Geometry.hull univ i.2.1.toCellScheme.faces {x₀, x₁} = univ) (hcard : 2 < i.1)
    (f : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α j)
    (g : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α k) :
    ∃ (l : TopFreeIndex.{u} α) (a : topFreeChart α j ↪[hullLanguage.{u} α] topFreeChart α l)
      (b : topFreeChart α k ↪[hullLanguage.{u} α] topFreeChart α l), a.comp f = b.comp g ∧
        2 < l.1 ∧ ∀ φ ψ : topFreeChart α i ↪[hullLanguage.{u} α] topFreeChart α l,
          φ (i.2.1.toChart x₀) = ψ (i.2.1.toChart x₀) →
            φ (i.2.1.toChart x₁) = ψ (i.2.1.toChart x₁) → φ = ψ := by
  obtain ⟨l, a, b, hab⟩ := exists_amalgam_topFreeChart hext hα h0 i j k f g
  refine ⟨l, a, b, hab, ?_, fun φ ψ ↦ eq_of_apply_eq_of_hull_eq_univ hgen φ ψ⟩
  let e : Fin i.1 ↪ Fin l.1 := ⟨fun x ↦ a (f x), a.injective.comp f.injective⟩
  exact hcard.trans_le (by simpa using Fintype.card_le_of_embedding e)

/-! ### The base stage -/

/-- At `ω` the hypotheses on the stage hold: it is a nonzero limit with countably many ordinals
below it. -/
private example : Order.IsSuccPrelimit ω ∧ 0 < ω ∧ (Set.Iio (ω : Ordinal.{u})).Countable :=
  ⟨Ordinal.isSuccLimit_omega0.isSuccPrelimit, Ordinal.omega0_pos,
    Set.countable_coe_iff.mp countable_Iio_omega0_coe⟩

/-- At `ω`, under the coatom extension property, which is assumed here (it is compiled,
`StageType.hasCoatomExtensions`), the age of
top-free charts is a Fraïssé class, with the amalgamation and joint embedding properties. -/
private example (hext : StageType.HasCoatomExtensions.{u} ω) :
    IsFraisse (topFreeAge.{u} ω) ∧ Amalgamation (topFreeAge.{u} ω) ∧
      JointEmbedding (topFreeAge.{u} ω) :=
  ⟨isFraisse_topFreeAge_omega hext,
    amalgamation_topFreeAge hext Ordinal.isSuccLimit_omega0.isSuccPrelimit Ordinal.omega0_pos,
    jointEmbedding_topFreeAge hext Ordinal.isSuccLimit_omega0.isSuccPrelimit Ordinal.omega0_pos⟩

/-- At `ω`, under the coatom extension property, which is assumed here (it is compiled,
`StageType.hasCoatomExtensions`), the age of
top-free charts has a countable Fraïssé limit; the countability of the function symbols derived at
a general stage agrees with the instance at `ω`. -/
private example (hext : StageType.HasCoatomExtensions.{u} ω) :
    ∃ (M : Bundled.{0} (hullLanguage.{u} ω).Structure) (_ : Countable M),
      IsFraisseLimit (topFreeAge.{u} ω) M :=
  exists_isFraisseLimit_topFreeAge hext Ordinal.isSuccLimit_omega0.isSuccPrelimit
    Ordinal.omega0_pos (Set.countable_coe_iff.mp countable_Iio_omega0_coe)

end VaughtConjecture
