/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.ClassicalLimit.Amalgamation
import VaughtConjecture.ClassicalLimit.Reconstruction

/-!
# Examples: reconstruction of partial evaluation and its special cases

Roadmap, the section "The top-free witnesses: the finite age and its classical limit", steps 4 and
5, with the special cases of semantic contract, item 11.  Every statement below about a structure
`M` assumes local chart coverage, `(hullLanguage α).age M ⊆ topFreeAge α`, or that `M` is a Fraïssé
limit of the age of top-free charts; only the last example assumes the coatom extension property.

* **Top-free charts are locally charted.**  The age of a top-free chart lies in the age of top-free
  charts (the hereditary property), so every statement under local chart coverage applies to a
  top-free chart, with no hypothesis on the stage; there the reconstructed realization is the face
  realization (`reconstruct_chart`).
* **The empty tuple** has the type of the empty chart, the only stage type on no points.
* **The one-point chart** gives its point the one-point type.  Whether a Fraïssé limit of the age
  of top-free charts can have a single point depends on whether every legal top-free stage type has
  at most one point; the library has no public legal stage type on two or more points, so this is
  not decided here.  Every Fraïssé limit of the age has a point.
* **A pair that is not closed** has no type: in a chart, when the pair is not a closed face; in a
  locally charted structure, when the substructure generated by the pair has more points.
* **Repeated coordinates.**  Evaluation is defined only on injective tuples; no chart relation
  holds at a tuple with a repeated point; such a tuple still lies in the points of a typed tuple;
  and a hull operation with equal arguments takes the default value.
* **The default value.**  Where no chart witness exists, the hull operation of a locally charted
  structure is its first argument.
* **Stage `0`.**  Every reconstructed type at stage `0` has only the label `⊥`.
* **The base stage `ω`, conditionally.**  Under the coatom extension property at `ω`, there is a
  countable carrier with a nonempty, exactly consistent, covering realization with legal top-free
  types, the reconstructed realization of a Fraïssé limit.
-/

universe u

namespace VaughtConjecture

open FirstOrder Language Structure Finset
open scoped Ordinal

variable {α : Ordinal.{u}}

/-! ### Top-free charts are locally charted -/

/-- The age of a top-free chart lies in the age of top-free charts. -/
private theorem age_topFreeChart_subset (i : TopFreeIndex.{u} α) :
    (hullLanguage.{u} α).age (topFreeChart α i) ⊆ topFreeAge α :=
  hereditary_topFreeAge _ (topFreeChart_mem_topFreeAge i)

/-- On a top-free chart, the hull operations of the chart are those of the reconstructed
realization, without any hypothesis on the stage. -/
private example (i : TopFreeIndex.{u} α) (ι : HullIndex.{u} α) (a b : topFreeChart α i) :
    funMap (hullLanguage.op ι) ![a, b] = (reconstruct α (topFreeChart α i)).hullOp ι a b :=
  funMap_op_eq_hullOp (age_topFreeChart_subset i) ι a b

/-- On a top-free chart, the reconstructed realization is the face realization. -/
private example (i : TopFreeIndex.{u} α) : reconstruct α i.2.1.Chart = i.2.1.faceRealization :=
  reconstruct_chart i.2.2.1

/-! ### The empty tuple -/

/-- Under local chart coverage, the empty tuple has the type of the empty chart. -/
private example {M : Type} [(hullLanguage.{u} α).Structure M]
    (hage : (hullLanguage.{u} α).age M ⊆ topFreeAge α) :
    (reconstruct α M).eval (Function.Embedding.ofIsEmpty : Fin 0 ↪ M) =
      some (TopFreeIndex.empty α).2.1 := by
  obtain ⟨i, e, b, hb⟩ :=
    exists_eq_trans_topFreeChart hage (Function.Embedding.ofIsEmpty : Fin 0 ↪ M)
  rw [← hb, reconstruct_eval_trans_chart i.2.2.1 e b, StageType.faceRealization_eval]
  obtain ⟨p, hp⟩ := Option.isSome_iff_exists.mp (i.2.1.isSome_restrictFace_of_zero b)
  rw [hp]
  exact congrArg some (StageType.eq_of_zero p _)

/-! ### The one-point chart -/

/-- In the one-point chart, the point has the one-point type. -/
private example :
    (reconstruct α (TopFreeIndex.point α).2.1.Chart).eval
      ((Function.Embedding.refl _).trans (TopFreeIndex.point α).2.1.toChart.toEmbedding) =
      some (TopFreeIndex.point α).2.1 :=
  (reconstruct_chart_eval (TopFreeIndex.point α).2.2.1 _).trans (StageType.restrictFace_refl _)

/-- A Fraïssé limit of the age of top-free charts has a point. -/
private example {M : Type} [(hullLanguage.{u} α).Structure M]
    [Countable (Σ l, (hullLanguage.{u} α).Functions l)] [Countable M]
    (hM : IsFraisseLimit (topFreeAge.{u} α) M) : Nonempty M :=
  (reconstruct_of_isFraisseLimit hM).1

/-! ### A pair that is not closed -/

/-- In the chart of a legal stage type, a pair of points that is not a closed face has no type. -/
private example {k : ℕ} {P : StageType.{u} α k} (hP : P.IsLegal) (t : Fin 2 ↪ Fin k)
    (ht : univ.map t ∉ P.toCellScheme.faces) :
    (reconstruct α P.Chart).eval (t.trans P.toChart.toEmbedding) = none := by
  rw [reconstruct_chart_eval hP, StageType.restrictFace_eq_none_iff]
  exact ht

/-- Under local chart coverage, a pair whose generated substructure has more points has no type. -/
private example {M : Type} [(hullLanguage.{u} α).Structure M]
    (hage : (hullLanguage.{u} α).age M ⊆ topFreeAge α) (t : Fin 2 ↪ M)
    (ht : (Substructure.closure (hullLanguage.{u} α) (Set.range t) : Set M) ≠ Set.range t) :
    (reconstruct α M).eval t = none :=
  Option.not_isSome_iff_eq_none.mp fun h ↦ ht ((isSome_reconstruct_eval_iff hage t).mp h)

/-! ### Repeated coordinates and the default value -/

section Repeated

variable {M : Type} [(hullLanguage.{u} α).Structure M]
  (hage : (hullLanguage.{u} α).age M ⊆ topFreeAge α)
include hage

/-- Under local chart coverage, no chart relation holds at a pair with a repeated point. -/
private example (a : M) (p : StageType.{u} α 2) (hp : p.IsLegal) :
    ¬ RelMap (hullLanguage.rel p hp) ![a, a] := fun h ↦
  absurd (injective_of_relMap_rel hage h (a₁ := 0) (a₂ := 1) rfl) (by decide)

/-- Under local chart coverage, a pair with a repeated point lies in the points of a typed tuple. -/
private example (a : M) :
    ∃ (m : ℕ) (u : Fin m ↪ M) (b : Fin 2 → Fin m), u ∘ b = ![a, a] ∧
      ((reconstruct α M).eval u).isSome :=
  exists_comp_eq_reconstruct_eval hage ![a, a]

/-- Under local chart coverage, a hull operation with equal arguments takes the default value. -/
private example (ι : HullIndex.{u} α) (a : M) : funMap (hullLanguage.op ι) ![a, a] = a := by
  rw [funMap_op_eq_hullOp hage, Realization.hullOp_self]

/-- Under local chart coverage, where no chart witness exists, a hull operation takes the default
value, the first argument. -/
private example (ι : HullIndex.{u} α) (a b : M)
    (h : ¬ ∃ g : Fin ι.arity ↪ M,
      (reconstruct α M).eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    funMap (hullLanguage.op ι) ![a, b] = a := by
  rw [funMap_op_eq_hullOp hage, Realization.hullOp_of_not_exists h]

end Repeated

/-! ### Stage `0` -/

/-- Under local chart coverage at stage `0`, every reconstructed type has only the label `⊥`. -/
private example {M : Type} [(hullLanguage.{u} 0).Structure M]
    (hage : (hullLanguage.{u} 0).age M ⊆ topFreeAge 0) {n : ℕ} (t : Fin n ↪ M)
    (p : StageType.{u} 0 n) (h : (reconstruct 0 M).eval t = some p) (d : Fin p.card) :
    p.label d = ⊥ :=
  (Label.atStage_zero_iff.mp (p.atStage d)).resolve_right (isTopFree_of_reconstruct_eval hage h d)

/-! ### The base stage `ω`, conditionally -/

/-- Under the coatom extension property at `ω`, there is a countable carrier with a nonempty,
exactly consistent, covering realization with legal top-free types: the reconstructed realization
of a Fraïssé limit of the age of top-free charts. -/
private example (hext : StageType.HasCoatomExtensions.{u} ω) :
    ∃ (M : Type) (_ : Countable M) (R : Realization.{u, 0} ω M), Nonempty M ∧ R.IsConsistent ∧
      R.IsCovering ∧ R.HasLegalTypes ∧
      ∀ ⦃n : ℕ⦄ (t : Fin n ↪ M) (p : StageType.{u} ω n), R.eval t = some p → p.IsTopFree := by
  obtain ⟨M, _, hM⟩ := exists_isFraisseLimit_topFreeAge_omega hext
  obtain ⟨h1, h2, h3, h4, h5, -⟩ := reconstruct_of_isFraisseLimit hM
  exact ⟨M, inferInstance, reconstruct ω M, h1, h2, h3, h4, h5⟩

end VaughtConjecture
