/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Geometry.IntervalPlan
import VaughtConjecture.Language.HullDefinability

/-!
# Examples: the defining formulas of the hull operations on small charts

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures", item 2, and "Hull
closure inside definable closure"); `HULL_ALGEBRA.md`, §§1 and 4; semantic contract, item 11 (the
special cases: empty carriers, repeated inputs, and the default values).

* **The chart on no points.**  There is no triple of points, so no formula with three free
  variables is satisfied.
* **The one-point chart.**  At the only triple, the chart witness formula fails (a chart witness
  has two distinct points at its generators) and the graph formula holds: the hull operation takes
  its default value, the first argument.
* **Repeated inputs.**  On any chart, at a pair `(a, a)` the chart witness formula fails at every
  third point, and the graph formula holds exactly at `a`, the default value.
* **A legal chart generated by two points.**  If two coordinates `i₀ ≠ i₁` of a legal type `P`
  generate all of its points, then for every coordinate `j` the chart witness formula of the hull
  index `(P, i₀, i₁, j)` has the single solution `j` over `(i₀, i₁)`, and every point of the chart
  is definable over `{i₀, i₁}` in the stage chart language.
* **Legality cannot be dropped from hull closure inside definable closure.**  `bare` is the stage
  type on four points with no cells whose faces are the intervals of `Fin 4`; it is not legal along
  the hull of `{0, 3}`, which is everything.  No relation of the stage chart language holds of a
  nonempty tuple of its points, so the transposition of `1` and `2` is an automorphism of its
  chart fixing `0` and `3`; hence the point `1` of the hull of `{0, 3}` is not definable over
  `{0, 3}`.  The plan of `bare` is rigid (the transposition does not preserve the intervals), so
  the failure is one of definability, not of rigidity: the stage chart language sees only the
  faces that carry a legal type.
* **The default value at two distinct points.**  No hull index has a chart witness in `bare`, so at
  the distinct points `0` and `3` the graph formula holds exactly at the first argument.
* **The default value under a chart embedding.**  Where no chart witness exists in a face, the graph
  formula at the image of the pair holds exactly at the image of the first argument.
-/

universe u

namespace VaughtConjecture.StageType

open FirstOrder Language Structure Finset

variable {α : Ordinal.{u}} {k k' : ℕ}

/-! ### The chart on no points -/

/-- On the chart on no points no formula with three free variables is satisfied: there is no
triple of points. -/
private example (P : StageType.{u} α 0) (ι : HullIndex.{u} α) :
    {v : Fin 3 → P.Chart | ι.graphFormula.Realize v} = ∅ :=
  Set.eq_empty_of_forall_notMem fun v _ ↦ (v 0 : Fin 0).elim0

/-! ### The one-point chart -/

/-- On a chart with one point, the chart witness formula fails at the only triple. -/
private example (P : StageType.{u} α 1) (ι : HullIndex.{u} α) :
    ¬ ι.chartWitnessFormula.Realize ![P.toChart 0, P.toChart 0, P.toChart 0] := by
  rw [realize_chartWitnessFormula]
  exact fun ⟨g, _, hl, hr, _⟩ ↦ ι.left_ne_right (g.injective (hl.trans hr.symm))

/-- On a chart with one point, the graph formula holds at the only triple: the default value. -/
private example (P : StageType.{u} α 1) (ι : HullIndex.{u} α) :
    ι.graphFormula.Realize ![P.toChart 0, P.toChart 0, P.toChart 0] := by
  rw [realize_graphFormula, Realization.hullOp_self]

/-! ### Repeated inputs -/

/-- At a repeated input the chart witness formula fails at every third point. -/
private example (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a z : Fin k) :
    ¬ ι.chartWitnessFormula.Realize ![P.toChart a, P.toChart a, P.toChart z] := by
  rw [realize_chartWitnessFormula]
  exact fun ⟨g, _, hl, hr, _⟩ ↦ ι.left_ne_right (g.injective (hl.trans hr.symm))

/-- At a repeated input the graph formula holds exactly at the default value, the first argument. -/
private example (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a z : Fin k) :
    ι.graphFormula.Realize ![P.toChart a, P.toChart a, P.toChart z] ↔ z = a := by
  rw [realize_graphFormula, Realization.hullOp_self, eq_comm]

/-! ### A legal chart generated by two points -/

section TwoGenerated

variable (P : StageType.{u} α k) (hP : P.IsLegal) {i₀ i₁ : Fin k} (hne : i₀ ≠ i₁)
  (hgen : Geometry.hull univ P.toCellScheme.faces {i₀, i₁} = univ)
include hP hne hgen

/-- Over the two generators of a legal chart, the chart witness formula of the hull index of the
chart with target `j` has exactly one solution, the point `j`. -/
private example (j w : Fin k) :
    (⟨k, P, hP, i₀, i₁, j, hne, hgen⟩ : HullIndex.{u} α).chartWitnessFormula.Realize
      ![P.toChart i₀, P.toChart i₁, P.toChart w] ↔ w = j := by
  have h : P.faceRealization.hullOp ⟨k, P, hP, i₀, i₁, j, hne, hgen⟩ i₀ i₁ = j :=
    hullOp_eq_of_restrictFace (g := .refl _) (restrictFace_refl P)
  rw [realize_chartWitnessFormula_iff_hullOp_eq_of_exists (a := i₀) (b := i₁) w
      ⟨.refl _, restrictFace_refl P, rfl, rfl⟩, h, eq_comm]

/-- Over the two generators of a legal chart, the graph formula of the same hull index has the same
single solution. -/
private example (j w : Fin k) :
    (⟨k, P, hP, i₀, i₁, j, hne, hgen⟩ : HullIndex.{u} α).graphFormula.Realize
      ![P.toChart i₀, P.toChart i₁, P.toChart w] ↔ w = j := by
  have h : P.faceRealization.hullOp ⟨k, P, hP, i₀, i₁, j, hne, hgen⟩ i₀ i₁ = j :=
    hullOp_eq_of_restrictFace (g := .refl _) (restrictFace_refl P)
  rw [realize_graphFormula, h, eq_comm]

/-- Every point of a legal chart generated by two points is definable over them in the stage
chart language. -/
private example (x : Fin k) :
    ({P.toChart i₀, P.toChart i₁} : Set P.Chart).Definable₁ (stageChartLanguage.{u} α)
      {P.toChart x} :=
  definable₁_singleton_of_mem_hull_pair (fun g hg _ ↦ hP.comap g hg)
    (by rw [hgen]; exact mem_univ x)

end TwoGenerated

/-! ### Legality cannot be dropped from hull closure inside definable closure -/

/-- A stage type on four points with no cells, whose faces are the intervals of `Fin 4`. -/
private def bare : StageType.{0} 0 4 where
  card := 0
  toCellScheme := ⟨univ, Geometry.intervalPlan univ, Fin.elim0, Fin.elim0⟩
  rows := ⟨fun s ↦ s.elim0⟩
  label := Fin.elim0
  isWellFormed := ⟨rfl, ⟨inferInstance, Geometry.isPlan_intervalPlan _, fun d ↦ d.elim0⟩⟩
  isCoded s := s.elim0
  isLawful := CellScheme.Rows.isLawful_of_isEmpty _
  atStage d := d.elim0

/-- No nonempty face of `bare` has a legal type: a legal type on a point has a cell, and the
restriction of `bare` has no cells. -/
private theorem not_isLegal_of_restrictFace_bare {m : ℕ} (g : Fin m ↪ Fin 4)
    {q : StageType.{0} 0 m} (hq : restrictFace g bare = some q) (hl : q.IsLegal) (x : Fin m) :
    False := by
  obtain ⟨hf, rfl⟩ := (restrictFace_eq_some_iff bare g).mp hq
  obtain ⟨d, -⟩ := hl.isComplete ({x}, 1)
    ⟨(bare.comap g hf).isPlan.singleton_mem (mem_univ x), Nat.one_pos, by simp⟩
  exact (bare.cellMap g d).elim0

/-- The transposition of the points `1` and `2` is an automorphism of the chart of `bare` in the
stage chart language: no relation holds of a nonempty tuple. -/
private def swapBare : bare.Chart ≃[stageChartLanguage.{0} 0] bare.Chart where
  toEquiv := bare.toChart.symm.trans ((Equiv.swap 1 2).trans bare.toChart)
  map_fun' f := (f : Empty).elim
  map_rel' {n} r xs := by
    obtain ⟨p, hp⟩ := r
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · exact iff_of_eq (congrArg (RelMap _) (funext fun i ↦ i.elim0))
    · -- the relations of the chart of `bare` are its closed faces (`relMap_toChartStructure`)
      change (∃ h, restrictFace ⟨_, h⟩ bare = some p) ↔ ∃ h, restrictFace ⟨xs, h⟩ bare = some p
      refine ⟨fun ⟨_, h⟩ ↦ ?_, fun ⟨_, h⟩ ↦ ?_⟩ <;>
        exact (not_isLegal_of_restrictFace_bare _ h hp ⟨0, hn⟩).elim

/-- The point `1` lies in the hull of `{0, 3}` in `bare`: every interval containing `0` and `3`
contains `1`. -/
private theorem mem_hull_bare :
    (1 : Fin 4) ∈ Geometry.hull univ bare.toCellScheme.faces {0, 3} := by
  refine Geometry.mem_hull.mpr ⟨mem_univ _, fun B hB hS ↦ ?_⟩
  -- the faces of `bare` are the intervals
  change B ∈ Geometry.intervalPlan univ at hB
  exact (Geometry.mem_intervalPlan.mp hB).2 0 (hS (by simp)) 3 (hS (by simp)) 1 (mem_univ _)
    (by decide) (by decide)

/-- **The default value at two distinct points**: no hull index has a chart witness in `bare`, so
at `0` and `3` the graph formula holds exactly at `0`. -/
private example (ι : HullIndex.{0} 0) (z : Fin 4) :
    ι.graphFormula.Realize ![bare.toChart 0, bare.toChart 3, bare.toChart z] ↔ z = 0 := by
  rw [realize_graphFormula, Realization.hullOp_of_not_exists
    fun ⟨g, hg, _⟩ ↦ not_isLegal_of_restrictFace_bare g hg ι.isLegal ι.left, eq_comm]

/-- **Legality cannot be dropped** from `definable₁_singleton_of_mem_hull_pair`: in the chart of
`bare`, which is not legal along the hull of `{0, 3}`, the point `1` of that hull is not definable
over `{0, 3}`, since the automorphism `swapBare` fixes `0` and `3` and moves `1` to `2`.  The plan
of `bare` is rigid, so this is a failure of definability, not of rigidity. -/
private example : (1 : Fin 4) ∈ Geometry.hull univ bare.toCellScheme.faces {0, 3} ∧
    ¬ ({bare.toChart 0, bare.toChart 3} : Set bare.Chart).Definable₁ (stageChartLanguage.{0} 0)
      {bare.toChart 1} := by
  refine ⟨mem_hull_bare, ?_⟩
  set A : Set bare.Chart := {bare.toChart 0, bare.toChart 3}
  rw [Set.Definable₁, Set.definable_iff_exists_formula_sum]
  rintro ⟨φ, hφ⟩
  have h1 := (Set.ext_iff.mp hφ ![bare.toChart 1]).mp rfl
  have h2 := (Set.ext_iff.mp hφ ![bare.toChart 2]).not.mp (by decide)
  have hσ : swapBare ∘ Sum.elim ((↑) : A → bare.Chart) ![bare.toChart 1] =
      Sum.elim (↑) ![bare.toChart 2] := by
    funext i
    rcases i with ⟨x, hx⟩ | i
    · rcases hx with rfl | rfl
      · exact Equiv.swap_apply_of_ne_of_ne (a := (1 : Fin 4)) (b := 2) (x := 0) (by decide)
          (by decide)
      · exact Equiv.swap_apply_of_ne_of_ne (a := (1 : Fin 4)) (b := 2) (x := 3) (by decide)
          (by decide)
    · rw [Fin.fin_one_eq_zero i]
      rfl
  have := (StrongHomClass.realize_formula swapBare φ).mpr h1
  rw [hσ] at this
  exact h2 this

/-! ### The default value under a chart embedding -/

/-- Where no chart witness exists in a face, the graph formula at the image of the pair holds
exactly at the image of the first argument. -/
private example {P : StageType.{u} α k} {Q : StageType.{u} α k'} {e : Fin k ↪ Fin k'}
    (he : restrictFace e Q = some P) (ι : HullIndex.{u} α) {a b : Fin k}
    (h : ¬ ∃ g : Fin ι.arity ↪ Fin k,
      restrictFace g P = some ι.type ∧ g ι.left = a ∧ g ι.right = b) (z : Fin k) :
    ι.graphFormula.Realize ![Q.toChart (e a), Q.toChart (e b), Q.toChart (e z)] ↔ z = a := by
  rw [realize_graphFormula_map he, realize_graphFormula, Realization.hullOp_of_not_exists h,
    eq_comm]

end VaughtConjecture.StageType
