/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Extension.PinnedExtension
import VaughtConjecture.Language.HullOperations
import VaughtConjecture.Language.Structure

/-!
# Examples: hull operations on small charts and their special cases

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures"); `HULL_ALGEBRA.md`,
§§1–5; semantic contract, item 11 (the special cases: empty carriers, repeated inputs, and the
default values).

* **The chart on no points.**  A stage type on no points has no cells, and its chart is empty.
  The hull language has no constant symbols, so the empty set is a substructure, and every
  substructure of the chart is the chart of the restriction to the empty face.
* **The one-point chart.**  `point` is the legal stage type on one point carried by the
  one-point scheme with the bottom label.  The empty set generates the empty substructure, and
  the face `{0}` is a substructure.
* **A value that is not the default.**  At the generators of a legal type, the hull operation of
  the type itself returns the target coordinate.
* **Repeated inputs.**  No relation holds of a tuple with a repeated point, and a hull operation
  with equal arguments takes its default value, the first argument.
* **A pair that is not closed.**  In any legal chart, the substructure generated by two points
  that do not form a closed face contains a further point, the generated substructure being the
  hull; this is why the hull language, and not the relational stage chart language, has the
  closed faces as its substructures.
* **Legality cannot be dropped.**  For a stage type on at least three points that is not legal,
  the two extreme points of the whole type form a substructure that is not a closed face.
* **The default value under a chart embedding.**  Where a hull operation takes its default value
  in a face, it takes it at the image in the larger chart.
* **The base stage.**  At `ω` the stage chart language is the base language, and the relational
  reduct of a chart (its structure in the stage chart language) is the structure of its face
  realization in the base language.
-/

universe u

namespace VaughtConjecture.StageType

open FirstOrder Language Structure Finset
open scoped Ordinal

variable {α : Ordinal.{u}} {k k' : ℕ}

/-! ### The chart on no points -/

/-- A stage type on no points has no cells, and its empty face is defined. -/
private example (P : StageType.{u} α 0) :
    P.card = 0 ∧ (restrictFace (Function.Embedding.refl (Fin 0)) P).isSome :=
  ⟨P.card_eq_zero, P.isSome_restrictFace_of_zero _⟩

/-- The chart on no points is empty. -/
private example (P : StageType.{u} α 0) : IsEmpty P.Chart :=
  inferInstanceAs (IsEmpty (Fin 0))

/-- Every substructure of the chart of a legal type on no points is the chart of a restriction to
the empty face. -/
private example (P : StageType.{u} α 0) (hP : P.IsLegal)
    (S : (hullLanguage.{u} α).Substructure P.Chart) :
    ∃ (g : Fin 0 ↪ Fin 0) (hg : univ.map g ∈ P.toCellScheme.faces),
      Nonempty (S ≃[hullLanguage.{u} α] (P.comap g hg).Chart) := by
  obtain ⟨m, g, hg, -, ⟨φ⟩⟩ := exists_equiv_comap hP S
  obtain rfl : m = 0 := by simpa using Fintype.card_le_of_embedding g
  exact ⟨g, hg, ⟨φ⟩⟩

/-! ### The one-point chart -/

/-- The one-point stage type: the one-point scheme with the bottom label. -/
private noncomputable abbrev point (α : Ordinal.{u}) : StageType.{u} α 1 :=
  Scheme.isLegal_onePoint.toStageType α

/-- The one-point stage type is legal. -/
private theorem isLegal_point (α : Ordinal.{u}) : (point α).IsLegal :=
  Scheme.isLegal_onePoint.isLegal_toStageType α

/-- The empty set generates the empty substructure of the one-point chart: the hull language has
no constant symbols. -/
private example : (point α).toChart 0 ∉
    Substructure.closure (hullLanguage.{u} α) ((point α).toChart '' (∅ : Finset (Fin 1))) := by
  rw [toChart_mem_closure_iff (isLegal_point α), Geometry.hull_eq_self (point α).isPlan.empty_mem
    (empty_subset _)]
  exact notMem_empty 0

/-- The single point of the one-point chart generates the whole chart. -/
private example : (point α).toChart 0 ∈
    Substructure.closure (hullLanguage.{u} α) ((point α).toChart '' ({0} : Finset (Fin 1))) := by
  rw [toChart_mem_closure_iff (isLegal_point α)]
  exact Geometry.subset_hull (subset_univ _) (mem_singleton_self 0)

/-- The face `{0}` of the one-point chart is a substructure containing its point. -/
private example : (point α).toChart 0 ∈
    (point α).faceSubstructure ((point α).isPlan.singleton_mem (mem_univ 0)) :=
  (toChart_mem_faceSubstructure _ 0).mpr (mem_singleton_self 0)

/-- On the one-point chart every hull operation takes its default value. -/
private example (ι : HullIndex.{u} α) (a b : Fin 1) :
    (point α).faceRealization.hullOp ι a b = a := by
  obtain rfl := Subsingleton.elim a b
  exact Realization.hullOp_self ι a

/-! ### Repeated inputs -/

/-- No relation holds of a tuple with a repeated point. -/
private example (P : StageType.{u} α k) {n : ℕ} (p : StageType.{u} α n) (hp : p.IsLegal)
    (xs : Fin n → P.Chart) (i j : Fin n) (hij : i ≠ j) (h : xs i = xs j) :
    ¬ RelMap (hullLanguage.rel p hp) xs :=
  fun ⟨hinj, _⟩ ↦ hij (hinj h)

/-- A hull operation with equal arguments takes its default value. -/
private example (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a : Fin k) :
    funMap (hullLanguage.op ι) ![P.toChart a, P.toChart a] = P.toChart a := by
  rw [funMap_chart, Realization.hullOp_self]

/-! ### A value that is not the default -/

/-- At the generators of a legal type, the hull operation of the type itself returns the target. -/
private example (P : StageType.{u} α k) (hP : P.IsLegal) {i₀ i₁ j : Fin k} (hne : i₀ ≠ i₁)
    (hgen : Geometry.hull univ P.toCellScheme.faces {i₀, i₁} = univ) :
    P.faceRealization.hullOp ⟨k, P, hP, i₀, i₁, j, hne, hgen⟩ i₀ i₁ = j :=
  hullOp_eq_of_restrictFace (g := .refl _) (restrictFace_refl P)

/-! ### A pair that is not closed -/

/-- In a legal chart, two points that do not form a closed face generate a substructure with a
further point. -/
private example (P : StageType.{u} α k) (hP : P.IsLegal) {a b : Fin k}
    (hab : ({a, b} : Finset (Fin k)) ∉ P.toCellScheme.faces) :
    ∃ x ∉ ({a, b} : Finset (Fin k)), P.toChart x ∈
      Substructure.closure (hullLanguage.{u} α) (P.toChart '' ({a, b} : Finset (Fin k))) := by
  have hne : Geometry.hull univ P.toCellScheme.faces {a, b} ≠ {a, b} :=
    fun h ↦ hab (P.isPlan.isConvexGeometry.hull_eq_self_iff.mp h)
  obtain ⟨x, hx, hxab⟩ := exists_of_ssubset
    (Finset.ssubset_iff_subset_ne.mpr ⟨Geometry.subset_hull (subset_univ _), hne.symm⟩)
  exact ⟨x, hxab, (toChart_mem_closure_iff hP _ x).mpr hx⟩

/-! ### Legality cannot be dropped -/

/-- For a stage type on at least three points that is not legal, the two extreme points of the
whole type form a substructure of its chart that is not a closed face: a chart witness at them
would be a reindexing of the whole type, which is not legal, so every hull operation takes its
default value there.  So the legality hypothesis of `mem_faces_of_substructure` is essential. -/
private example (P : StageType.{u} α k) (hP : ¬ P.IsLegal) (hk : 3 ≤ k) :
    ∃ (S : (hullLanguage.{u} α).Substructure P.Chart) (C : Finset (Fin k)),
      (∀ x, P.toChart x ∈ S ↔ x ∈ C) ∧ C ∉ P.toCellScheme.faces := by
  obtain ⟨a, b, hab, hext⟩ := card_eq_two.mp (P.isPlan.card_extremes P.univ_mem_faces
    (by rw [card_univ, Fintype.card_fin]; omega))
  have hgen : Geometry.hull univ P.toCellScheme.faces {a, b} = univ :=
    (P.hull_eq_univ_iff_extremes_subset).mpr hext.le
  -- There is no chart witness at two distinct points of `{a, b}`.
  have hdef (ι : HullIndex.{u} α) {x y : Fin k} (hx : x ∈ ({a, b} : Finset (Fin k)))
      (hy : y ∈ ({a, b} : Finset (Fin k))) (hxy : x ≠ y) :
      P.faceRealization.hullOp ι x y = x := by
    refine Realization.hullOp_of_not_exists ?_
    rintro ⟨g, hg, hl, hr⟩
    have hxy' : ({x, y} : Finset (Fin k)) = {a, b} := by
      refine eq_of_subset_of_card_le (insert_subset_iff.mpr ⟨hx, singleton_subset_iff.mpr hy⟩) ?_
      rw [card_pair hab, card_pair hxy]
    have hrange : univ.map g = univ := by
      rw [map_univ_eq_hull_of_restrictFace hg ι.hull_eq_univ, hl, hr, hxy', hgen]
    have hsurj : Function.Surjective g := fun z ↦ by
      have hz : z ∈ univ.map g := hrange ▸ mem_univ z
      obtain ⟨j, -, hj⟩ := mem_map.mp hz
      exact ⟨j, hj⟩
    let e := Equiv.ofBijective g ⟨g.injective, hsurj⟩
    have hge : g = e.toEmbedding := Function.Embedding.ext fun _ ↦ rfl
    rw [faceRealization_eval, hge, restrictFace_equiv, Option.some_inj] at hg
    have hl : (P.reindex e).IsLegal := hg ▸ ι.isLegal
    refine hP ?_
    have := hl.reindex e.symm
    rwa [reindex_reindex, Equiv.symm_trans_self, reindex_refl] at this
  refine ⟨⟨P.toChart '' ({a, b} : Finset (Fin k)), ?_⟩, {a, b}, fun x ↦ ?_, fun hC ↦ ?_⟩
  · intro n f
    induction f using hullLanguage.functions_induction with
    | op ι =>
      intro xs hxs
      obtain ⟨x, hx, hxx⟩ := hxs 0
      obtain ⟨y, hy, hyy⟩ := hxs 1
      have hxs : xs = ![P.toChart x, P.toChart y] :=
        funext (Fin.forall_fin_two.mpr ⟨hxx.symm, hyy.symm⟩)
      rw [hxs, funMap_chart]
      refine Set.mem_image_of_mem _ ?_
      rcases eq_or_ne x y with rfl | hxy
      · rw [Realization.hullOp_self]
        exact hx
      · rw [hdef ι hx hy hxy]
        exact hx
  · exact P.toChart.injective.mem_set_image
  · have h := P.isPlan.isConvexGeometry.hull_eq_self_iff.mpr hC
    rw [hgen] at h
    have := congrArg Finset.card h
    rw [card_univ, Fintype.card_fin, card_pair hab] at this
    omega

/-! ### The default value under a chart embedding -/

/-- Where a hull operation takes its default value in a face, it takes the default value at the
image in the larger chart. -/
private example {P : StageType.{u} α k} {Q : StageType.{u} α k'} {e : Fin k ↪ Fin k'}
    (he : restrictFace e Q = some P) (ι : HullIndex.{u} α) {a b : Fin k}
    (h : ¬ ∃ g : Fin ι.arity ↪ Fin k,
      P.faceRealization.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    Q.faceRealization.hullOp ι (e a) (e b) = e a := by
  rw [hullOp_map_of_restrictFace he, Realization.hullOp_of_not_exists h]

/-- The chart embedding of the identity face of the one-point type into itself preserves the
default value at the repeated input. -/
private example (ι : HullIndex.{u} α) :
    (point α).faceRealization.hullOp ι (Function.Embedding.refl (Fin 1) 0)
      (Function.Embedding.refl (Fin 1) 0) =
        Function.Embedding.refl (Fin 1) ((point α).faceRealization.hullOp ι 0 0) :=
  hullOp_map_of_restrictFace (restrictFace_refl (point α)) ι 0 0

/-! ### The base stage -/

/-- At `ω` the stage chart language is the base language. -/
private example : stageChartLanguage.{u} ω = baseLanguage.{u} :=
  stageChartLanguage_omega

/-- At `ω` the relational reduct of a chart is the structure of its face realization in the base
language. -/
private example (P : StageType.{u} ω k) {n : ℕ} (p : StageType.{u} ω n) (hp : p.IsLegal)
    (xs : Fin n → P.Chart) :
    RelMap (stageChartLanguage.symbol p hp) xs ↔
      @RelMap baseLanguage.{u} (Fin k) P.faceRealization.toStructure n
        (baseLanguage.symbol p hp) xs :=
  Iff.rfl

/-- At `ω` the structure of a realization in the stage chart language is its structure in the base
language. -/
private example {M : Type*} (R : Realization.{u} ω M) :
    R.toChartStructure = R.toStructure :=
  rfl

/-- The hull language at `ω` has countably many function and relation symbols. -/
private example : Countable (Σ n, (hullLanguage.{u} ω).Functions n) ∧
    Countable (Σ n, (hullLanguage.{u} ω).Relations n) :=
  ⟨inferInstance, inferInstance⟩

end VaughtConjecture.StageType
