/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Extension.PinnedExtension
import VaughtConjecture.Language.HullOperations
import VaughtConjecture.Language.Structure

/-!
# Examples: hull operations on small charts and their special cases

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures"); `HULL_ALGEBRA.md`,
§§1–5; semantic contract, item 11 (the special cases: empty carriers, repeated inputs, and the
default values).

* **The chart on no points.**  A stage type on no points has no cells, and its chart is empty.
  The hull language has no constant symbols, so the empty set is a substructure, and every
  substructure of the chart is the chart of the restriction to the empty face.
* **The one-point chart.**  `point` is the legal stage type on one point carried by the
  one-point scheme with the bottom label.  The empty set generates the empty substructure, and
  the face `{0}` is a substructure.
* **Repeated inputs.**  No relation holds of a tuple with a repeated point, and a hull operation
  with equal arguments takes its default value, the first argument.
* **A pair that is not closed.**  In any legal chart, the substructure generated by two points
  that do not form a closed face contains a further point, the generated substructure being the
  hull; this is why the hull language, and not the relational stage chart language, has the
  closed faces as its substructures.
* **The default value under a chart embedding.**  Where a hull operation takes its default value
  in a face, it takes it at the image in the larger chart.
* **The base stage.**  At `ω` the stage chart language is the base language, and the relational
  reduct of a chart is the structure of its face realization in the base language.
-/

universe u

namespace VaughtConjecture.StageType

open FirstOrder Language Structure Finset
open scoped Ordinal

variable {α : Ordinal.{u}} {k k' : ℕ}

/-! ### The chart on no points -/

/-- A stage type on no points has no cells, and its empty face is defined. -/
private example (P : StageType.{u} α 0) :
    P.card = 0 ∧ (restrictFace (Function.Embedding.refl (Fin 0)) P).isSome :=
  ⟨P.card_eq_zero, P.isSome_restrictFace_of_zero _⟩

/-- The chart on no points is empty. -/
private example (P : StageType.{u} α 0) : IsEmpty P.Chart :=
  inferInstanceAs (IsEmpty (Fin 0))

/-- Every substructure of the chart of a legal type on no points is the chart of a restriction to
the empty face. -/
private example (P : StageType.{u} α 0) (hP : P.IsLegal)
    (S : (hullLanguage.{u} α).Substructure P.Chart) :
    ∃ (g : Fin 0 ↪ Fin 0) (hg : univ.map g ∈ P.toCellScheme.faces),
      Nonempty (S ≃[hullLanguage.{u} α] (P.comap g hg).Chart) := by
  obtain ⟨m, g, hg, -, ⟨φ⟩⟩ := exists_equiv_comap hP S
  obtain rfl : m = 0 := by simpa using Fintype.card_le_of_embedding g
  exact ⟨g, hg, ⟨φ⟩⟩

/-! ### The one-point chart -/

/-- The one-point stage type: the one-point scheme with the bottom label. -/
private noncomputable abbrev point (α : Ordinal.{u}) : StageType.{u} α 1 :=
  Scheme.isLegal_onePoint.toStageType α

/-- The one-point stage type is legal. -/
private theorem isLegal_point (α : Ordinal.{u}) : (point α).IsLegal :=
  Scheme.isLegal_onePoint.isLegal_toStageType α

/-- The empty set generates the empty substructure of the one-point chart: the hull language has
no constant symbols. -/
private example : (point α).toChart 0 ∉
    Substructure.closure (hullLanguage.{u} α) ((point α).toChart '' (∅ : Finset (Fin 1))) := by
  rw [toChart_mem_closure_iff (isLegal_point α), Geometry.hull_eq_self (point α).isPlan.empty_mem
    (empty_subset _)]
  exact notMem_empty 0

/-- The single point of the one-point chart generates the whole chart. -/
private example : (point α).toChart 0 ∈
    Substructure.closure (hullLanguage.{u} α) ((point α).toChart '' ({0} : Finset (Fin 1))) := by
  rw [toChart_mem_closure_iff (isLegal_point α)]
  exact Geometry.subset_hull (subset_univ _) (mem_singleton_self 0)

/-- The face `{0}` of the one-point chart is a substructure containing its point. -/
private example : (point α).toChart 0 ∈
    (point α).faceSubstructure ((point α).isPlan.singleton_mem (mem_univ 0)) :=
  (toChart_mem_faceSubstructure _ 0).mpr (mem_singleton_self 0)

/-- On the one-point chart every hull operation takes its default value. -/
private example (ι : HullIndex.{u} α) (a b : Fin 1) :
    (point α).faceRealization.hullOp ι a b = a := by
  obtain rfl := Subsingleton.elim a b
  exact Realization.hullOp_self ι a

/-! ### Repeated inputs -/

/-- No relation holds of a tuple with a repeated point. -/
private example (P : StageType.{u} α k) {n : ℕ} (p : StageType.{u} α n) (hp : p.IsLegal)
    (xs : Fin n → P.Chart) (i j : Fin n) (hij : i ≠ j) (h : xs i = xs j) :
    ¬ RelMap (hullLanguage.rel p hp) xs :=
  fun ⟨hinj, _⟩ ↦ hij (hinj h)

/-- A hull operation with equal arguments takes its default value. -/
private example (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a : Fin k) :
    funMap (hullLanguage.op ι) ![P.toChart a, P.toChart a] = P.toChart a := by
  rw [funMap_chart, Realization.hullOp_self]

/-! ### A pair that is not closed -/

/-- In a legal chart, two points that do not form a closed face generate a substructure with a
further point. -/
private example (P : StageType.{u} α k) (hP : P.IsLegal) {a b : Fin k}
    (hab : ({a, b} : Finset (Fin k)) ∉ P.toCellScheme.faces) :
    ∃ x ∉ ({a, b} : Finset (Fin k)), P.toChart x ∈
      Substructure.closure (hullLanguage.{u} α) (P.toChart '' ({a, b} : Finset (Fin k))) := by
  have hne : Geometry.hull univ P.toCellScheme.faces {a, b} ≠ {a, b} :=
    fun h ↦ hab (P.isPlan.isConvexGeometry.hull_eq_self_iff.mp h)
  obtain ⟨x, hx, hxab⟩ := exists_of_ssubset
    (Finset.ssubset_iff_subset_ne.mpr ⟨Geometry.subset_hull (subset_univ _), hne.symm⟩)
  exact ⟨x, hxab, (toChart_mem_closure_iff hP _ x).mpr hx⟩

/-! ### The default value under a chart embedding -/

/-- Where a hull operation takes its default value in a face, it takes the default value at the
image in the larger chart. -/
private example {P : StageType.{u} α k} {Q : StageType.{u} α k'} {e : Fin k ↪ Fin k'}
    (he : restrictFace e Q = some P) (ι : HullIndex.{u} α) {a b : Fin k}
    (h : ¬ ∃ g : Fin ι.arity ↪ Fin k,
      P.faceRealization.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    Q.faceRealization.hullOp ι (e a) (e b) = e a := by
  rw [hullOp_comp he, Realization.hullOp_of_not_exists h]

/-- The chart embedding of the identity face of the one-point type into itself preserves the
default value at the repeated input. -/
private example (ι : HullIndex.{u} α) :
    (point α).faceRealization.hullOp ι (Function.Embedding.refl (Fin 1) 0)
      (Function.Embedding.refl (Fin 1) 0) =
        Function.Embedding.refl (Fin 1) ((point α).faceRealization.hullOp ι 0 0) :=
  hullOp_comp (restrictFace_refl (point α)) ι 0 0

/-! ### The base stage -/

/-- At `ω` the stage chart language is the base language. -/
private example : stageChartLanguage.{u} ω = baseLanguage.{u} :=
  stageChartLanguage_omega

/-- At `ω` the relational reduct of a chart is the structure of its face realization in the base
language. -/
private example (P : StageType.{u} ω k) {n : ℕ} (p : StageType.{u} ω n) (hp : p.IsLegal)
    (xs : Fin n → P.Chart) :
    RelMap (hullLanguage.rel p hp) xs ↔
      @RelMap baseLanguage.{u} (Fin k) P.faceRealization.toStructure n
        (baseLanguage.symbol p hp) xs :=
  Iff.rfl

/-- At `ω` the structure of a realization in the stage chart language is its structure in the base
language. -/
private example {M : Type*} (R : Realization.{u} ω M) :
    R.toChartStructure = R.toStructure :=
  rfl

/-- The hull language at `ω` has countably many function and relation symbols. -/
private example : Countable (Σ n, (hullLanguage.{u} ω).Functions n) ∧
    Countable (Σ n, (hullLanguage.{u} ω).Relations n) :=
  ⟨inferInstance, inferInstance⟩

end VaughtConjecture.StageType
