/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.ModelTheory.Substructures
import VaughtConjecture.Language.Basic
import VaughtConjecture.Realization.Partial

/-!
# Hull operations and the two-charts theorem for finite charts

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures", items 1, 3 and 4 for
chart embeddings, and 5, for finite charts); `HULL_ALGEBRA.md`, §§1–3 and 5; semantic contract,
item 10 (uniqueness of the charts that witness a hull operation, and preservation by embeddings
proved from those charts).

These are the facts about finite charts that the classical limit of the top-free witnesses uses
(roadmap, "The top-free witnesses: the finite age and its classical limit"): in the hull language
the finite charts are closed under substructures, up to isomorphism (the hereditary property of
their age), and chart embeddings are exactly the embeddings of the corresponding finite
structures.

**Languages.**  The **stage chart language** `stageChartLanguage α` has one `n`-ary relation
symbol for each legal stage type at stage `α` on `n` points and no function symbols; at `α = ω` it
is the base language (`stageChartLanguage_omega`, by `rfl`).  A **hull index** (`HullIndex α`) is
a legal stage type with an ordered pair of distinct coordinates generating all of its points
(equivalently, the pair contains the extreme points of the type,
`StageType.hull_eq_univ_iff_extremes_subset`, and is then exactly the pair of its two extreme
points, `HullIndex.extremes_eq`) and a target coordinate.  The **hull language**
`hullLanguage α`, the definitional expansion `L^h_α` of the roadmap, is the sum
(`FirstOrder.Language.sum`) of the stage chart language and the language `hullSymbols α` with one
binary function symbol for each hull index.  Its symbols are countable
when there are countably many ordinals below `α` (`hullLanguage.countable_functions`,
`hullLanguage.countable_relations`, and instances at `ω`).  The stage chart language is
`Language.{0, u + 1}` and the hull symbols are `Language.{u + 1, 0}`: hull indices, like stage
types, live in `Type (u + 1)`; the hull language is `Language.{u + 1, u + 1}`.

**Realizations.**  A realization `R` is a structure of the stage chart language
(`Realization.toChartStructure`: the relation of `p` holds of an injective tuple of type `p`) and
of the hull language (`Realization.toHullStructure`).  A **chart witness** of a hull index `ι` at
points `a` and `b` is a tuple of type `ι.type` with `a` and `b` at the generators.  The **hull
operation** `R.hullOp ι a b` (`HULL_ALGEBRA.md`, §1) is the target point of a chosen chart witness
at `a` and `b`, if there is one, and otherwise the **default value** `a`
(`Realization.hullOp_of_not_exists`); in particular `R.hullOp ι a a = a`
(`Realization.hullOp_self`).

**The two-charts theorem.**  Two faces of a chart with the same type `q`, generated by the
coordinates `i₀` and `i₁`, that agree at `i₀` and `i₁` are equal
(`StageType.eq_of_restrictFace_eq_some`).  Both have the hull of the two common points as their
points (`StageType.map_univ_eq_hull_of_restrictFace`), so they differ by a permutation of the
coordinates of `q` that preserves its faces and fixes its generators; such a permutation is the
identity by rigidity of plans (`Geometry.IsPlan.apply_eq_of_mem_hull`).  Hence on the face
realization of a chart the chosen value of a hull operation is the canonical one: at the points of
a face of type `ι.type` at the generators it is the point of that face at the target
(`StageType.hullOp_eq_of_restrictFace`).

**Charts.**  The **chart** `P.Chart` of a stage type `P` on `k` points is a copy of `Fin k`
(identified with it by `P.toChart`), with the structure of the face realization of `P` in the
hull language, whose reduct to the stage chart language is the structure of the face realization
in that language: the relation of a legal type `p` holds of a tuple exactly when the tuple is
injective and spans a closed face of type `p`, a face that is not closed carrying no relation
(`StageType.relMap_chart`), and the function symbols are the hull operations
(`StageType.funMap_chart`).  For finite charts:

* a nonsingleton closed set is the hull of its two extreme points: this part of roadmap, Layer 2,
  item 1 is the plan geometry of Layer 1 (`Geometry.IsConvexGeometry.hull_extremes`,
  `Geometry.IsPlan.extremes_hull`) and the canonical finite hulls of `Realization.finiteHull`;
  here it is read on hull indices (`StageType.hull_eq_univ_iff_extremes_subset`,
  `HullIndex.extremes_eq`);
* every hull operation takes its value in the hull of its two arguments
  (`StageType.hullOp_mem_hull`, `HULL_ALGEBRA.md`, §2), and every point of the hull of two
  distinct points of a legal chart is the value of a hull operation at them
  (`StageType.exists_hullOp_eq_of_mem_hull`, §3);
* a **chart embedding**, a face map along which the restriction is literal, commutes with every
  hull operation, the default value included (`StageType.hullOp_map_of_restrictFace`), carries
  closed faces to closed faces and hulls to hulls (`StageType.map_mem_faces_iff_of_restrictFace`,
  `StageType.hull_map_of_restrictFace`), and is an embedding of charts
  (`StageType.chartEmbedding`); conversely every embedding of charts one of which is legal is a
  chart embedding (`StageType.restrictFace_toEmbedding`, `StageType.exists_eq_chartEmbedding`);
* the substructures of the chart of a legal type are exactly its closed faces
  (`StageType.mem_faces_of_substructure`, `StageType.faceSubstructure`), the substructure
  generated by a set is its hull (`StageType.toChart_mem_closure_iff`), and every substructure,
  with the induced structure, is isomorphic to the chart of the literal restriction to its points
  (`StageType.exists_equiv_comap`).

The first-order definability of the hull operations (roadmap, Layer 2, item 2) and their
preservation by embeddings of infinite realizations are not part of this file.  On a realization
that is not the face realization of a chart, `Realization.hullOp` is defined by a choice; that the
choice does not matter on exactly consistent covering realizations is the two-charts theorem for
realizations (`Realization.eq_of_eval_eq_some`, `Realization.hullOp_eq_of_eval`), which is not
part of this file either: it is proved in `VaughtConjecture.Realization.TwoCharts`, with the
preservation of the hull operations by embeddings of realizations.

## Placement

This file belongs to Layer 2 of `roadmap/README.md`.
-/

universe u v

namespace VaughtConjecture

open FirstOrder Language Structure Finset
open scoped Ordinal

/-! ### The stage chart language -/

/-- The **stage chart language** at stage `α`: one `n`-ary relation symbol for each legal stage
type at stage `α` on `n` points, and no function symbols.  At `α = ω` it is the base language
(`stageChartLanguage_omega`). -/
def stageChartLanguage (α : Ordinal.{u}) : Language.{0, u + 1} where
  Functions _ := Empty
  Relations n := {p : StageType.{u} α n // p.IsLegal}

/-- At stage `ω` the stage chart language is the base language. -/
theorem stageChartLanguage_omega : stageChartLanguage.{u} ω = baseLanguage.{u} :=
  rfl

namespace stageChartLanguage

variable {α : Ordinal.{u}}

/-- The stage chart language is relational. -/
instance isRelational : IsRelational (stageChartLanguage.{u} α) :=
  fun _ ↦ inferInstanceAs (IsEmpty Empty)

/-- The relation symbol of a legal stage type. -/
def symbol {n : ℕ} (p : StageType.{u} α n) (hp : p.IsLegal) :
    (stageChartLanguage.{u} α).Relations n :=
  (⟨p, hp⟩ : {p : StageType.{u} α n // p.IsLegal})

end stageChartLanguage

/-! ### Hull indices -/

/-- A **hull index** at stage `α` (`HULL_ALGEBRA.md`, §1): a legal stage type `type` on `arity`
points, an ordered pair of distinct coordinates `left`, `right` that generate all of its points
(the hull of `{left, right}` is everything; equivalently the pair contains the extreme points,
`StageType.hull_eq_univ_iff_extremes_subset`, and is then exactly the pair of the two extreme
points, `HullIndex.extremes_eq`), and a target coordinate. -/
structure HullIndex (α : Ordinal.{u}) : Type (u + 1) where
  /-- The number of points. -/
  arity : ℕ
  /-- The stage type. -/
  type : StageType.{u} α arity
  /-- The stage type is legal. -/
  isLegal : type.IsLegal
  /-- The first generator. -/
  left : Fin arity
  /-- The second generator. -/
  right : Fin arity
  /-- The target coordinate. -/
  target : Fin arity
  /-- The two generators are distinct. -/
  left_ne_right : left ≠ right
  /-- The two generators generate all points. -/
  hull_eq_univ : Geometry.hull univ type.toCellScheme.faces {left, right} = univ

/-- A set of points of a stage type generates all points exactly when it contains the extreme
points of the whole ground set. -/
theorem StageType.hull_eq_univ_iff_extremes_subset {α : Ordinal.{u}} {n : ℕ}
    (t : StageType.{u} α n) {S : Finset (Fin n)} :
    Geometry.hull univ t.toCellScheme.faces S = univ ↔
      Geometry.extremes t.toCellScheme.faces univ ⊆ S :=
  t.isPlan.isConvexGeometry.hull_eq_ground_iff_extremes_subset (subset_univ S)

namespace HullIndex

variable {α : Ordinal.{u}}

/-- The two generators of a hull index are exactly the extreme points of its stage type. -/
theorem extremes_eq (ι : HullIndex.{u} α) :
    Geometry.extremes ι.type.toCellScheme.faces univ = {ι.left, ι.right} := by
  rw [← ι.hull_eq_univ, ι.type.isPlan.extremes_hull (subset_univ _) card_le_two]

/-- **Countably many hull indices**: if there are countably many ordinals below the stage `α`, there
are countably many hull indices at stage `α`. -/
theorem countable (hα : (Set.Iio α).Countable) : Countable (HullIndex.{u} α) := by
  have := StageType.countable hα
  let F : HullIndex.{u} α → Σ n, StageType.{u} α n × Fin n × Fin n × Fin n :=
    fun ι ↦ ⟨ι.arity, ι.type, ι.left, ι.right, ι.target⟩
  refine Function.Injective.countable (f := F) ?_
  rintro ⟨n, p, _, l, r, t, _, _⟩ ⟨n', p', _, l', r', t', _, _⟩ h
  obtain ⟨rfl, h⟩ := Sigma.mk.inj_iff.mp h
  obtain ⟨rfl, rfl, rfl, rfl⟩ : p = p' ∧ l = l' ∧ r = r' ∧ t = t' := by
    simpa only [Prod.mk.injEq] using eq_of_heq h
  rfl

end HullIndex

/-! ### The language of the hull operations -/

/-- The **hull symbols** at stage `α`: one binary function symbol for each hull index, no function
symbols of other arities, and no relation symbols. -/
def hullSymbols (α : Ordinal.{u}) : Language.{u + 1, 0} where
  Functions n := match n with
    | 2 => HullIndex.{u} α
    | _ => PEmpty
  Relations _ := Empty

/-- The **hull language** at stage `α`, the language `L^h_α` of `roadmap/README.md`: the stage
chart language with one binary function symbol for each hull index, the symbol of its hull
operation. -/
abbrev hullLanguage (α : Ordinal.{u}) : Language.{u + 1, u + 1} :=
  (stageChartLanguage.{u} α).sum (hullSymbols.{u} α)

namespace hullLanguage

variable {α : Ordinal.{u}}

/-- The binary function symbol of a hull index. -/
def op (ι : HullIndex.{u} α) : (hullLanguage.{u} α).Functions 2 :=
  Sum.inr ι

/-- The relation symbol of a legal stage type. -/
def rel {n : ℕ} (p : StageType.{u} α n) (hp : p.IsLegal) : (hullLanguage.{u} α).Relations n :=
  Sum.inl (stageChartLanguage.symbol p hp)

/-- **Function symbols of the hull language.**  A property of all function symbols holds once it
holds of the symbols of the hull indices. -/
@[elab_as_elim]
theorem functions_induction {motive : ∀ n, (hullLanguage.{u} α).Functions n → Prop}
    (op : ∀ ι : HullIndex.{u} α, motive 2 (op ι)) :
    ∀ {n : ℕ} (f : (hullLanguage.{u} α).Functions n), motive n f
  | _, Sum.inl f => isEmptyElim (α := Empty) f
  | 0, Sum.inr f => (f : PEmpty).elim
  | 1, Sum.inr f => (f : PEmpty).elim
  | 2, Sum.inr ι => op ι
  | _ + 3, Sum.inr f => (f : PEmpty).elim

/-- **Countably many function symbols**: if there are countably many ordinals below the stage `α`,
the hull language at `α` has countably many function symbols. -/
theorem countable_functions (hα : (Set.Iio α).Countable) :
    Countable (Σ n, (hullLanguage.{u} α).Functions n) := by
  have := HullIndex.countable hα
  have (n : ℕ) : Countable ((hullSymbols.{u} α).Functions n) := by
    rcases n with _ | _ | _ | n
    · exact inferInstanceAs (Countable PEmpty)
    · exact inferInstanceAs (Countable PEmpty)
    · exact inferInstanceAs (Countable (HullIndex.{u} α))
    · exact inferInstanceAs (Countable PEmpty)
  have (n : ℕ) : Countable ((hullLanguage.{u} α).Functions n) :=
    inferInstanceAs (Countable (Empty ⊕ (hullSymbols.{u} α).Functions n))
  infer_instance

/-- **Countably many relation symbols**: if there are countably many ordinals below the stage `α`,
the hull language at `α` has countably many relation symbols. -/
theorem countable_relations (hα : (Set.Iio α).Countable) :
    Countable (Σ n, (hullLanguage.{u} α).Relations n) := by
  have := StageType.countable hα
  have (n : ℕ) : Countable ((hullLanguage.{u} α).Relations n) :=
    inferInstanceAs (Countable ({p : StageType.{u} α n // p.IsLegal} ⊕ Empty))
  infer_instance

/-- The hull language at stage `ω` has countably many function symbols. -/
instance countable_functions_omega : Countable (Σ n, (hullLanguage.{u} ω).Functions n) :=
  countable_functions (Set.countable_coe_iff.mp countable_Iio_omega0_coe)

/-- The hull language at stage `ω` has countably many relation symbols. -/
instance countable_relations_omega : Countable (Σ n, (hullLanguage.{u} ω).Relations n) :=
  countable_relations (Set.countable_coe_iff.mp countable_Iio_omega0_coe)

end hullLanguage

/-! ### Realizations as structures of the hull language -/

namespace Realization

variable {α : Ordinal.{u}} {M : Type v} (R : Realization.{u, v} α M) {n : ℕ}

/-- The **structure of a realization** in the stage chart language: the relation of a legal stage
type `p` holds of a tuple exactly when the tuple is injective and has the type `p`. -/
@[instance_reducible] def toChartStructure : (stageChartLanguage.{u} α).Structure M where
  RelMap p xs := ∃ h : Function.Injective xs, R.eval ⟨xs, h⟩ = some p.1

/-- On an injective tuple, a relation holds in the structure of a realization exactly when the
tuple has the stage type of the relation. -/
theorem relMap_toChartStructure (p : StageType.{u} α n) (hp : p.IsLegal) (t : Fin n ↪ M) :
    @RelMap _ M R.toChartStructure n (stageChartLanguage.symbol p hp) t ↔ R.eval t = some p :=
  ⟨fun ⟨_, h⟩ ↦ h, fun h ↦ ⟨t.injective, h⟩⟩

open Classical in
/-- The **hull operation** of a hull index `ι` in a realization (`HULL_ALGEBRA.md`, §1).  A
**chart witness** of `ι` at `a` and `b` is a tuple of type `ι.type` with the points `a` and `b` at
the generators.  The hull operation at `a` and `b` is the target point of a chosen chart witness, if
there is one, a **witnessed value**, and otherwise the **default value** `a` (a witnessed value
may coincide with `a`).  On the face realization of a chart the
choice does not matter (`StageType.hullOp_eq_of_restrictFace`), nor on any exactly consistent
covering realization (`Realization.hullOp_eq_of_eval`). -/
noncomputable def hullOp (ι : HullIndex.{u} α) (a b : M) : M :=
  if h : ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b then
    h.choose ι.target
  else a

variable {R}

/-- Where there is a chart witness at `a` and `b`, the hull operation is the target point of one. -/
theorem hullOp_spec {ι : HullIndex.{u} α} {a b : M}
    (h : ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b ∧
      R.hullOp ι a b = g ι.target := by
  refine ⟨h.choose, h.choose_spec.1, h.choose_spec.2.1, h.choose_spec.2.2, ?_⟩
  simp only [hullOp, h, ↓reduceDIte]

/-- **The default value**: where there is no chart witness at `a` and `b`, the hull operation is its
first argument. -/
theorem hullOp_of_not_exists {ι : HullIndex.{u} α} {a b : M}
    (h : ¬ ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    R.hullOp ι a b = a := by
  simp only [hullOp, h, ↓reduceDIte]

/-- **Repeated inputs** give the default value: the generators of a hull index are distinct, so no
injective tuple has the same point at both. -/
@[simp] theorem hullOp_self (ι : HullIndex.{u} α) (a : M) : R.hullOp ι a a = a :=
  hullOp_of_not_exists fun ⟨g, _, hl, hr⟩ ↦ ι.left_ne_right (g.injective (hl.trans hr.symm))

variable (R)

/-- The hull operations of a realization, as a structure of the hull symbols. -/
@[instance_reducible] noncomputable def toHullSymbolsStructure :
    (hullSymbols.{u} α).Structure M where
  funMap {n} f xs := match n, f with
    | 2, ι => R.hullOp ι (xs 0) (xs 1)
    | 0, f => (f : PEmpty).elim
    | 1, f => (f : PEmpty).elim
    | _ + 3, f => (f : PEmpty).elim
  RelMap r := (r : Empty).elim

/-- The **structure of a realization in the hull language**: the relations of the stage chart
language (`toChartStructure`) and the hull operations (`hullOp`). -/
@[instance_reducible] noncomputable def toHullStructure : (hullLanguage.{u} α).Structure M :=
  @sumStructure _ _ M R.toChartStructure R.toHullSymbolsStructure

/-- In the structure of a realization, the symbol of a hull index is its hull operation. -/
theorem funMap_toHullStructure (ι : HullIndex.{u} α) (xs : Fin 2 → M) :
    @funMap _ M R.toHullStructure 2 (hullLanguage.op ι) xs = R.hullOp ι (xs 0) (xs 1) :=
  rfl

/-- In the structure of a realization, the relations are those of `toChartStructure`. -/
theorem relMap_toHullStructure (p : StageType.{u} α n) (hp : p.IsLegal) (xs : Fin n → M) :
    @RelMap _ M R.toHullStructure n (hullLanguage.rel p hp) xs ↔
      ∃ h : Function.Injective xs, R.eval ⟨xs, h⟩ = some p :=
  Iff.rfl

end Realization

/-! ### The two-charts theorem -/

namespace StageType

variable {α : Ordinal.{u}} {k k' m n : ℕ}

/-- **The support of a two-generated face.**  If the face of a chart `P` along `g` is a type `q`
generated by the coordinates `i₀`, `i₁`, then the points of the face are the hull in `P` of the
two points `g i₀`, `g i₁`. -/
theorem map_univ_eq_hull_of_restrictFace {P : StageType.{u} α k} {q : StageType.{u} α m}
    {g : Fin m ↪ Fin k} {i₀ i₁ : Fin m} (hg : restrictFace g P = some q)
    (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ) :
    univ.map g = Geometry.hull univ P.toCellScheme.faces {g i₀, g i₁} := by
  obtain ⟨hf, rfl⟩ := (restrictFace_eq_some_iff P g).mp hg
  refine Subset.antisymm (fun x hx ↦ ?_) (Geometry.hull_subset hf ?_)
  · obtain ⟨j, -, rfl⟩ := mem_map.mp hx
    have hj : j ∈ Geometry.hull univ (P.comap g hf).toCellScheme.faces {i₀, i₁} :=
      by rw [hgen]; exact mem_univ j
    rw [hull_comap] at hj
    simpa using hj
  · simp [insert_subset_iff]

/-- **The two-charts theorem** for finite charts (`HULL_ALGEBRA.md`, §1): two faces of a chart
with the same type `q`, generated by the coordinates `i₀` and `i₁`, that agree at `i₀` and `i₁`
are equal.  Both faces have the hull of the two common points as their points
(`map_univ_eq_hull_of_restrictFace`), so one is the other composed with a permutation of the
coordinates of `q`; this permutation preserves the faces of `q` and fixes its generators, hence
is the identity by rigidity of plans (`Geometry.IsPlan.apply_eq_of_mem_hull`). -/
theorem eq_of_restrictFace_eq_some {P : StageType.{u} α k} {q : StageType.{u} α m}
    {g g' : Fin m ↪ Fin k} {i₀ i₁ : Fin m}
    (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ)
    (hg : restrictFace g P = some q) (hg' : restrictFace g' P = some q)
    (h₀ : g i₀ = g' i₀) (h₁ : g i₁ = g' i₁) : g = g' := by
  have hr : univ.map g = univ.map g' := by
    rw [map_univ_eq_hull_of_restrictFace hg hgen, map_univ_eq_hull_of_restrictFace hg' hgen, h₀,
      h₁]
  -- The permutation `σe` with `g' ∘ σe = g`.
  obtain ⟨σe, hσe⟩ := Function.Embedding.exists_trans_eq (e := g') (g := g) fun j ↦ by
    have hj := mem_map_of_mem g (mem_univ j)
    rw [hr, mem_map] at hj
    obtain ⟨j', -, h⟩ := hj
    exact ⟨j', h⟩
  have hσ (j : Fin m) : g' (σe j) = g j := congrArg (· j) hσe
  obtain ⟨hf, rfl⟩ := (restrictFace_eq_some_iff P g).mp hg
  obtain ⟨hf', hq⟩ := (restrictFace_eq_some_iff P g').mp hg'
  -- `σ` preserves the faces of `q`.
  have hface : ∀ C ∈ (P.comap g hf).toCellScheme.faces,
      C.map σe ∈ (P.comap g hf).toCellScheme.faces := by
    intro C hC
    rw [← hq]
    have hmap : (C.map σe).map g' = C.map g := by
      rw [map_map, hσe]
    simp only [comap_toScheme, Scheme.mem_comap_faces] at hC ⊢
    rwa [hmap]
  have hfix : ∀ i ∈ ({i₀, i₁} : Finset (Fin m)), σe i = i := by
    simp only [mem_insert, mem_singleton, forall_eq_or_imp, forall_eq]
    exact ⟨g'.injective ((hσ i₀).trans h₀), g'.injective ((hσ i₁).trans h₁)⟩
  refine Function.Embedding.ext fun j ↦ ?_
  have hj := (P.comap g hf).isPlan.apply_eq_of_mem_hull hface (subset_univ _) hfix
    (by rw [hgen]; exact mem_univ j)
  rw [← hσ j]
  exact congrArg g' hj

/-! ### Charts as finite structures of the hull language -/

/-- The **chart** of a stage type `P` on `k` points: its points `Fin k`, read as a finite structure
of the hull language (roadmap, Layer 2, item 5).  The relation of a legal type `p` holds of a tuple
exactly when the tuple is injective and spans a closed face of `P` of type `p`, and the hull
operations are those of the face realization of `P`.  It is a type synonym of `Fin k`, so that
this structure, which depends on `P`, is not an instance on `Fin k`. -/
@[nolint unusedArguments]
def Chart (_P : StageType.{u} α k) : Type :=
  Fin k

variable (P : StageType.{u} α k)

instance : Fintype P.Chart :=
  inferInstanceAs (Fintype (Fin k))

instance : DecidableEq P.Chart :=
  inferInstanceAs (DecidableEq (Fin k))

/-- The points of a stage type, read as the points of its chart. -/
def toChart : Fin k ≃ P.Chart :=
  Equiv.refl _

noncomputable instance : (hullLanguage.{u} α).Structure P.Chart :=
  P.faceRealization.toHullStructure

/-- The relational reduct of the chart: its structure in the stage chart language. -/
noncomputable instance : (stageChartLanguage.{u} α).Structure P.Chart :=
  P.faceRealization.toChartStructure

/-- The structure of the chart in the hull language expands its relational reduct. -/
instance : (LHom.sumInl : stageChartLanguage.{u} α →ᴸ hullLanguage.{u} α).IsExpansionOn P.Chart :=
  ⟨fun f _ ↦ (f : Empty).elim, fun _ _ ↦ rfl⟩

/-- The relations of the chart are the closed faces with their types. -/
theorem relMap_chart (p : StageType.{u} α n) (hp : p.IsLegal) (t : Fin n ↪ Fin k) :
    RelMap (hullLanguage.rel p hp) (P.toChart ∘ t) ↔ restrictFace t P = some p :=
  ⟨fun ⟨_, h⟩ ↦ h, fun h ↦ ⟨t.injective, h⟩⟩

/-- The function symbols of the chart are the hull operations of its face realization. -/
@[simp] theorem funMap_chart (ι : HullIndex.{u} α) (a b : Fin k) :
    funMap (hullLanguage.op ι) ![P.toChart a, P.toChart b] =
      P.toChart (P.faceRealization.hullOp ι a b) :=
  rfl

/-! ### Hull operations on charts -/

variable {P}

/-- **The value of a hull operation on a chart**: at the points of a face of type `ι.type` at the
generators, the hull operation is the point of that face at the target.  By the two-charts
theorem it does not depend on the choice in `Realization.hullOp`. -/
theorem hullOp_eq_of_restrictFace {ι : HullIndex.{u} α} {g : Fin ι.arity ↪ Fin k}
    (hg : restrictFace g P = some ι.type) :
    P.faceRealization.hullOp ι (g ι.left) (g ι.right) = g ι.target := by
  obtain ⟨g', hg', h₀, h₁, he⟩ := Realization.hullOp_spec (R := P.faceRealization)
    ⟨g, hg, rfl, rfl⟩
  rw [he, eq_of_restrictFace_eq_some ι.hull_eq_univ hg' hg h₀ h₁]

/-- **Hull operations stay in the two-point hull** (`HULL_ALGEBRA.md`, §2): the value of a hull
operation at `a` and `b` lies in the hull of `{a, b}`. -/
theorem hullOp_mem_hull (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a b : Fin k) :
    P.faceRealization.hullOp ι a b ∈ Geometry.hull univ P.toCellScheme.faces {a, b} := by
  by_cases h : ∃ g : Fin ι.arity ↪ Fin k,
      P.faceRealization.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b
  · obtain ⟨g, hg, rfl, rfl, he⟩ := Realization.hullOp_spec h
    rw [he, ← map_univ_eq_hull_of_restrictFace hg ι.hull_eq_univ]
    exact mem_map_of_mem g (mem_univ _)
  · rw [Realization.hullOp_of_not_exists h]
    exact Geometry.subset_hull (subset_univ _) (mem_insert_self a _)

/-- **Legality along a two-point hull from a hull operation**: if `b` is the value at `a` and `b`
of a hull operation, with `a ≠ b`, then the restriction of the chart to the hull of `{a, b}` is
legal: the value `b` differs from the default value `a`, so it is a witnessed value, the target of
a chart witness, whose points are that hull and whose type is the legal type of the hull index. -/
theorem isLegal_comap_of_hullOp_eq_right {a b : Fin k} (hab : a ≠ b) {ι : HullIndex.{u} α}
    (hι : P.faceRealization.hullOp ι a b = b) {m : ℕ} (g : Fin m ↪ Fin k)
    (hg : univ.map g ∈ P.toCellScheme.faces)
    (hgH : univ.map g = Geometry.hull univ P.toCellScheme.faces {a, b}) :
    (P.comap g hg).IsLegal := by
  by_cases h : ∃ w : Fin ι.arity ↪ Fin k,
      P.faceRealization.eval w = some ι.type ∧ w ι.left = a ∧ w ι.right = b
  · obtain ⟨w, hw, hl, hr, -⟩ := Realization.hullOp_spec h
    have hrange := map_univ_eq_hull_of_restrictFace hw ι.hull_eq_univ
    rw [hl, hr, ← hgH] at hrange
    obtain ⟨σ, rfl⟩ := Function.Embedding.exists_trans_eq (e := w) (g := g) fun j ↦ by
      have hj := mem_map_of_mem g (mem_univ j)
      rw [← hrange, mem_map] at hj
      obtain ⟨i, -, hi⟩ := hj
      exact ⟨i, hi⟩
    refine ι.isLegal.restrictFace σ ?_
    rw [restrictFace_trans P w σ hw]
    exact restrictFace_of_mem P _ hg
  · exact absurd ((Realization.hullOp_of_not_exists h).symm.trans hι) hab

/-- **Every point of a two-point hull is the value of a hull operation** (`HULL_ALGEBRA.md`, §3):
for distinct points `a`, `b` of a chart, every point of the hull of `{a, b}` is the value at `a`
and `b` of the hull operation of the type of the hull, with its generators at `a` and `b`.

Legality is assumed only along the hull of `{a, b}` (`hleg`), where it is needed for that type to
index a hull operation; it holds for every pair when the chart is legal (`IsLegal.comap`).  It is
also necessary: if `b` is the value of a hull operation at `a` and `b`, the value is not the
default, so it comes from a chart witness, whose type is a legal face on the hull of `{a, b}`
(`isLegal_comap_of_hullOp_eq_right`). -/
theorem exists_hullOp_eq_of_mem_hull {a b x : Fin k} (hab : a ≠ b)
    (hleg : ∀ {m : ℕ} (g : Fin m ↪ Fin k) (hg : univ.map g ∈ P.toCellScheme.faces),
      univ.map g = Geometry.hull univ P.toCellScheme.faces {a, b} → (P.comap g hg).IsLegal)
    (hx : x ∈ Geometry.hull univ P.toCellScheme.faces {a, b}) :
    ∃ ι : HullIndex.{u} α, P.faceRealization.hullOp ι a b = x := by
  let g : Fin #(Geometry.hull univ P.toCellScheme.faces {a, b}) ↪ Fin k :=
    ((Geometry.hull univ P.toCellScheme.faces {a, b}).orderEmbOfFin rfl).toEmbedding
  have hgH : univ.map g = Geometry.hull univ P.toCellScheme.faces {a, b} :=
    map_orderEmbOfFin_univ _ rfl
  have hH : univ.map g ∈ P.toCellScheme.faces := by
    rw [hgH]
    exact P.isPlan.isConvexGeometry.hull_mem
  have hmem {y : Fin k} (hy : y ∈ Geometry.hull univ P.toCellScheme.faces {a, b}) :
      ∃ j, g j = y := by
    rw [← hgH, mem_map] at hy
    obtain ⟨j, -, h⟩ := hy
    exact ⟨j, h⟩
  obtain ⟨i₀, hi₀⟩ := hmem (Geometry.subset_hull (subset_univ _) (mem_insert_self a _))
  obtain ⟨i₁, hi₁⟩ := hmem (Geometry.subset_hull (subset_univ _)
    (mem_insert_of_mem (mem_singleton_self b)))
  obtain ⟨j, hj⟩ := hmem hx
  have hgen : Geometry.hull univ (P.comap g hH).toCellScheme.faces {i₀, i₁} = univ := by
    rw [hull_comap]
    refine eq_univ_of_forall fun i ↦ mem_preimage.mpr ?_
    simpa [hi₀, hi₁, hgH] using mem_map_of_mem g (mem_univ i)
  let ι : HullIndex.{u} α := ⟨_, P.comap g hH, hleg g hH hgH, i₀, i₁, j,
    fun h ↦ hab (hi₀.symm.trans ((congrArg g h).trans hi₁)), hgen⟩
  have h := hullOp_eq_of_restrictFace (ι := ι) (restrictFace_of_mem P g hH)
  rw [hi₀, hi₁, hj] at h
  exact ⟨ι, h⟩

/-- **Hull operations are preserved by chart embeddings, including the default value**
(roadmap, Layer 2, item 3 for chart embeddings; `HULL_ALGEBRA.md`, §5).  Let `e` be a face map
along which the restriction of `Q` is `P`.  A chart witness in `P` is carried to a chart witness in
`Q`; and a chart witness in `Q` at `e a`, `e b` has as points the hull of `{e a, e b}`, which lies
in the closed range of `e`, so it reflects to a chart witness in `P`.  Hence the default value is
taken in both or in neither. -/
theorem hullOp_map_of_restrictFace {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) (ι : HullIndex.{u} α) (a b : Fin k) :
    Q.faceRealization.hullOp ι (e a) (e b) = e (P.faceRealization.hullOp ι a b) := by
  by_cases h : ∃ w : Fin ι.arity ↪ Fin k,
      P.faceRealization.eval w = some ι.type ∧ w ι.left = a ∧ w ι.right = b
  · obtain ⟨w, hw, rfl, rfl, hval⟩ := Realization.hullOp_spec h
    have hwQ : restrictFace (w.trans e) Q = some ι.type := by
      rw [← restrictFace_trans Q e w he]
      exact hw
    rw [hval, ← Function.Embedding.trans_apply, ← Function.Embedding.trans_apply,
      ← Function.Embedding.trans_apply, hullOp_eq_of_restrictFace hwQ]
  · rw [Realization.hullOp_of_not_exists h, Realization.hullOp_of_not_exists]
    rintro ⟨g, hg, hl, hr⟩
    have hge : univ.map e ∈ Q.toCellScheme.faces := (restrictFace_eq_some_iff Q e).mp he |>.1
    have hsub : univ.map g ⊆ univ.map e := by
      rw [map_univ_eq_hull_of_restrictFace hg ι.hull_eq_univ, hl, hr]
      exact Geometry.hull_subset hge (by simp [insert_subset_iff])
    obtain ⟨w, rfl⟩ := Function.Embedding.exists_trans_eq (e := e) fun j ↦ by
      simpa using hsub (mem_map_of_mem g (mem_univ j))
    refine h ⟨w, ?_, e.injective hl, e.injective hr⟩
    rw [faceRealization_eval, restrictFace_trans Q e w he]
    exact hg

/-! ### Chart embeddings -/

/-- The **chart embedding** of a face map `e` along which the restriction of `Q` is `P`: the map
`e` as an embedding of structures of the hull language.  It preserves and reflects the relations
by the guarded composition law of face maps, and the hull operations by
`hullOp_map_of_restrictFace`. -/
noncomputable def chartEmbedding {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) :
    P.Chart ↪[hullLanguage.{u} α] Q.Chart where
  toEmbedding := P.toChart.symm.toEmbedding.trans (e.trans Q.toChart.toEmbedding)
  map_fun' {n} f xs := by
    induction f using hullLanguage.functions_induction with
    | op ι => exact (hullOp_map_of_restrictFace he ι (xs 0) (xs 1)).symm
  map_rel' {n} r xs := by
    rcases r with ⟨p, hp⟩ | r
    · -- the relations of the two charts are their closed faces (`relMap_toHullStructure`)
      change (∃ h, restrictFace ⟨e ∘ xs, h⟩ Q = some p) ↔ ∃ h, restrictFace ⟨xs, h⟩ P = some p
      refine ⟨fun ⟨h, hq⟩ ↦ ⟨h.of_comp, ?_⟩, fun ⟨h, hq⟩ ↦ ⟨e.injective.comp h, ?_⟩⟩
      · rw [restrictFace_trans Q e _ he]
        exact hq
      · rw [← hq, restrictFace_trans Q e ⟨xs, h⟩ he]
        rfl
    · exact (r : Empty).elim

/-- The chart embedding of a face map is the face map. -/
@[simp] theorem chartEmbedding_toChart {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) (x : Fin k) :
    chartEmbedding he (P.toChart x) = Q.toChart (e x) :=
  rfl

/-- Chart embeddings compose along composed face maps. -/
theorem chartEmbedding_comp {k'' : ℕ} {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {R : StageType.{u} α k''} {e : Fin k ↪ Fin k'} {e' : Fin k' ↪ Fin k''}
    (he : restrictFace e Q = some P) (he' : restrictFace e' R = some Q) :
    (chartEmbedding he').comp (chartEmbedding he) =
      chartEmbedding (e := e.trans e') (by rw [← restrictFace_trans R e' e he']; exact he) :=
  Embedding.ext fun _ ↦ rfl

/-- **Closed images of chart embeddings** (roadmap, Layer 2, item 4 for chart embeddings): along a
face map `e` along which the restriction of `Q` is `P`, a set of points of `P` is a closed face of
`P` exactly when its image is a closed face of `Q`. -/
theorem map_mem_faces_iff_of_restrictFace {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) {C : Finset (Fin k)} :
    C.map e ∈ Q.toCellScheme.faces ↔ C ∈ P.toCellScheme.faces := by
  obtain ⟨hf, rfl⟩ := (restrictFace_eq_some_iff Q e).mp he
  simp

/-- **Hulls of images under chart embeddings** (roadmap, Layer 2, item 4 for chart embeddings):
along a face map `e` along which the restriction of `Q` is `P`, the hull of the image of a set is
the image of its hull. -/
theorem hull_map_of_restrictFace {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) (s : Finset (Fin k)) :
    Geometry.hull univ Q.toCellScheme.faces (s.map e) =
      (Geometry.hull univ P.toCellScheme.faces s).map e := by
  obtain ⟨hf, rfl⟩ := (restrictFace_eq_some_iff Q e).mp he
  rw [hull_comap, map_preimage_eq_of_subset_range]
  intro x hx
  have hsub := Geometry.hull_subset hf (map_subset_map.mpr (subset_univ s)) (mem_coe.mp hx)
  obtain ⟨y, -, rfl⟩ := mem_map.mp hsub
  exact ⟨y, rfl⟩

/-! ### Substructures of charts -/

/-- **Substructures of a legal chart are closed faces** (roadmap, Layer 2, item 5): the points of
a substructure of the chart of a legal type form a closed face.  The hull of a set is the hull of
at most two of its points (`Geometry.IsPlan.exists_subset_card_le_two_hull_eq`), and every point
of the hull of two distinct points is the value of a hull operation at them
(`exists_hullOp_eq_of_mem_hull`).

Legality is essential: for a stage type that is not legal on at least three points, the two
extreme points of the whole type form a substructure that is not closed, since a chart witness at
them would be a reindexing of the whole type, which is not legal, so every hull operation takes its
default value there.  The stage type `bare` on three points with no cells is such a type
(`VaughtConjecture.Language.HullOperationsExamples`). -/
theorem mem_faces_of_substructure (hP : P.IsLegal) (S : (hullLanguage.{u} α).Substructure P.Chart)
    {C : Finset (Fin k)} (hC : ∀ x, P.toChart x ∈ S ↔ x ∈ C) : C ∈ P.toCellScheme.faces := by
  refine P.isPlan.isConvexGeometry.hull_eq_self_iff.mp
    (Subset.antisymm (fun x hx ↦ ?_) (Geometry.subset_hull (subset_univ C)))
  obtain ⟨T, hTC, hT2, hTH⟩ := P.isPlan.exists_subset_card_le_two_hull_eq (subset_univ C)
  rw [← hTH] at hx
  rcases Nat.lt_or_ge 1 #T with h1 | h1
  · obtain ⟨a, b, hab, rfl⟩ := card_eq_two.mp (le_antisymm hT2 h1)
    obtain ⟨ι, rfl⟩ := exists_hullOp_eq_of_mem_hull hab (fun g hg _ ↦ hP.comap g hg) hx
    have ha : P.toChart a ∈ S := (hC a).mpr (hTC (mem_insert_self a _))
    have hb : P.toChart b ∈ S := (hC b).mpr (hTC (by simp))
    have h := S.fun_mem (hullLanguage.op ι) ![P.toChart a, P.toChart b]
      (Fin.forall_fin_two.mpr ⟨ha, hb⟩)
    rw [funMap_chart] at h
    exact (hC _).mp h
  · have hT : T ∈ P.toCellScheme.faces := by
      rcases T.eq_empty_or_nonempty with rfl | hne
      · exact P.isPlan.empty_mem
      · obtain ⟨a, rfl⟩ := card_eq_one.mp (le_antisymm h1 hne.card_pos)
        exact P.isPlan.singleton_mem (mem_univ a)
    rw [Geometry.hull_eq_self hT (subset_univ T)] at hx
    exact hTC hx

/-- The **substructure of a closed face**: the points of a closed face of a chart are closed under
the hull operations (`hullOp_mem_hull`). -/
def faceSubstructure {C : Finset (Fin k)} (hC : C ∈ P.toCellScheme.faces) :
    (hullLanguage.{u} α).Substructure P.Chart where
  carrier := P.toChart '' C
  fun_mem {n} f := by
    induction f using hullLanguage.functions_induction with
    | op ι =>
      intro xs hxs
      obtain ⟨a, ha, hxa⟩ := hxs 0
      obtain ⟨b, hb, hxb⟩ := hxs 1
      have hxs : xs = ![P.toChart a, P.toChart b] :=
        funext (Fin.forall_fin_two.mpr ⟨hxa.symm, hxb.symm⟩)
      rw [hxs, funMap_chart]
      refine Set.mem_image_of_mem _ (Geometry.hull_subset hC ?_ (hullOp_mem_hull P ι a b))
      exact insert_subset_iff.mpr ⟨ha, singleton_subset_iff.mpr hb⟩

/-- The points of the substructure of a closed face are the points of the face. -/
@[simp] theorem toChart_mem_faceSubstructure {C : Finset (Fin k)}
    (hC : C ∈ P.toCellScheme.faces) (x : Fin k) : P.toChart x ∈ P.faceSubstructure hC ↔ x ∈ C :=
  P.toChart.injective.mem_set_image

/-- The substructure generated by a set lies in its hull, which is a substructure.  No legality is
needed: the hull is closed under the hull operations by the plan geometry (`hullOp_mem_hull`). -/
theorem mem_hull_of_toChart_mem_closure {s : Finset (Fin k)} {x : Fin k}
    (hx : P.toChart x ∈ Substructure.closure (hullLanguage.{u} α) (P.toChart '' s)) :
    x ∈ Geometry.hull univ P.toCellScheme.faces s := by
  have hle : Substructure.closure (hullLanguage.{u} α) (P.toChart '' s) ≤
      P.faceSubstructure P.isPlan.isConvexGeometry.hull_mem :=
    Substructure.closure_le.mpr <| Set.image_mono fun y hy ↦
      Geometry.subset_hull (subset_univ s) hy
  exact (toChart_mem_faceSubstructure _ x).mp (hle hx)

/-- **The substructure generated by a set is its hull** (roadmap, Layer 2, item 5): in the chart
of a legal type, a point lies in the substructure generated by a set exactly when it lies in the
hull of the set.  Legality is used only for the inclusion of the hull in the generated substructure
(`mem_faces_of_substructure`), where it is essential; the other inclusion is
`mem_hull_of_toChart_mem_closure`. -/
theorem toChart_mem_closure_iff (hP : P.IsLegal) (s : Finset (Fin k)) (x : Fin k) :
    P.toChart x ∈ Substructure.closure (hullLanguage.{u} α) (P.toChart '' s) ↔
      x ∈ Geometry.hull univ P.toCellScheme.faces s := by
  classical
  set S := Substructure.closure (hullLanguage.{u} α) (P.toChart '' s)
  refine ⟨mem_hull_of_toChart_mem_closure, fun hx ↦ ?_⟩
  · -- the points of the generated substructure form a closed face containing `s`
    have hC : univ.filter (fun y ↦ P.toChart y ∈ S) ∈ P.toCellScheme.faces :=
      mem_faces_of_substructure hP S fun y ↦ by simp
    have hsub : s ⊆ univ.filter (fun y ↦ P.toChart y ∈ S) := fun y hy ↦
      mem_filter.mpr ⟨mem_univ y, Substructure.subset_closure (Set.mem_image_of_mem _ hy)⟩
    exact (mem_filter.mp (Geometry.hull_subset hC hsub hx)).2

/-- **Every substructure of a legal chart is the chart of a literal restriction** (roadmap,
Layer 2, item 5): its points are the points of a closed face `g` of the stage type, and with the
induced structure it is isomorphic to the chart of the restriction `P.comap g hg`, by the chart
embedding of `g`.  Legality is essential, through `mem_faces_of_substructure`: the points of the
substructure must form a closed face. -/
theorem exists_equiv_comap (hP : P.IsLegal) (S : (hullLanguage.{u} α).Substructure P.Chart) :
    ∃ (m : ℕ) (g : Fin m ↪ Fin k) (hg : univ.map g ∈ P.toCellScheme.faces),
      (∀ x, P.toChart x ∈ S ↔ x ∈ univ.map g) ∧
        Nonempty (S ≃[hullLanguage.{u} α] (P.comap g hg).Chart) := by
  classical
  set C : Finset (Fin k) := univ.filter (fun x ↦ P.toChart x ∈ S)
  have hCS : ∀ x, P.toChart x ∈ S ↔ x ∈ C := fun x ↦ by simp [C]
  let g : Fin #C ↪ Fin k := (C.orderEmbOfFin rfl).toEmbedding
  have hgC : univ.map g = C := map_orderEmbOfFin_univ C rfl
  have hg : univ.map g ∈ P.toCellScheme.faces := by
    rw [hgC]
    exact mem_faces_of_substructure hP S hCS
  refine ⟨_, g, hg, fun x ↦ by rw [hgC]; exact hCS x, ?_⟩
  let φ := chartEmbedding (restrictFace_of_mem P g hg)
  have hrange : φ.toHom.range = S := by
    ext y
    obtain ⟨x, rfl⟩ := P.toChart.surjective y
    rw [Hom.mem_range, hCS]
    conv_rhs => rw [← hgC, mem_map]
    constructor
    · rintro ⟨z, hz⟩
      obtain ⟨j, rfl⟩ := (P.comap g hg).toChart.surjective z
      exact ⟨j, mem_univ j, P.toChart.injective hz⟩
    · rintro ⟨j, -, rfl⟩
      exact ⟨(P.comap g hg).toChart j, rfl⟩
  rw [← hrange]
  exact ⟨φ.equivRange.symm⟩

/-! ### Embeddings of charts -/

/-- **Chart embeddings are exactly the embeddings** (roadmap, Layer 2, item 5): every embedding
`φ` of the chart of `P` into the chart of `Q`, read on the points of `P` and `Q`, is a face map
along which the restriction of `Q` is `P`, provided `P` or `Q` is legal.

If `P` is legal, its relation holds of the points of `P` in order, so it holds of their image.  If
`Q` is legal, the image of `φ` is a substructure of the chart of `Q`, hence a closed face
(`mem_faces_of_substructure`) whose restriction is legal; its relation holds of the image, so it
holds of the points of `P`, and the restriction is `P`.  Legality cannot be dropped altogether:
on the stage type `bare` on three points with no cells, every hull operation takes its default
value and no relation holds of a nonempty tuple, so a transposition of two points that does not
preserve the faces is an embedding of charts but not a face map
(`VaughtConjecture.Language.HullOperationsExamples`). -/
theorem restrictFace_toEmbedding {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    (h : P.IsLegal ∨ Q.IsLegal) (φ : P.Chart ↪[hullLanguage.{u} α] Q.Chart) :
    restrictFace
      (P.toChart.toEmbedding.trans (φ.toEmbedding.trans Q.toChart.symm.toEmbedding)) Q =
        some P := by
  rcases h with hP | hQ
  · have h := (φ.map_rel (hullLanguage.rel P hP)
      (P.toChart ∘ Function.Embedding.refl (Fin k))).mpr
      ((relMap_chart P P hP _).mpr (restrictFace_refl P))
    exact (relMap_chart Q P hP _).mp h
  set t : Fin k ↪ Fin k' :=
    P.toChart.toEmbedding.trans (φ.toEmbedding.trans Q.toChart.symm.toEmbedding)
  -- the image of `φ` is a closed face of `Q`
  have hf : univ.map t ∈ Q.toCellScheme.faces := by
    refine mem_faces_of_substructure hQ φ.toHom.range fun y ↦ ?_
    rw [Hom.mem_range, mem_map]
    constructor
    · rintro ⟨z, hz⟩
      obtain ⟨x, rfl⟩ := P.toChart.surjective z
      exact ⟨x, mem_univ x, Q.toChart.injective hz⟩
    · rintro ⟨x, -, rfl⟩
      exact ⟨P.toChart x, rfl⟩
  have hq := hQ.comap t hf
  have hQt : restrictFace t Q = some (Q.comap t hf) := restrictFace_of_mem Q t hf
  have h1 := (relMap_chart Q _ hq t).mpr hQt
  have h2 := (φ.map_rel (hullLanguage.rel _ hq)
    (P.toChart ∘ Function.Embedding.refl (Fin k))).mp h1
  have h3 := (relMap_chart P _ hq _).mp h2
  rw [restrictFace_refl, Option.some_inj] at h3
  rw [hQt, h3]

/-- Every embedding of the chart of `P` into the chart of `Q` is the chart embedding of a face map,
provided `P` or `Q` is legal (`restrictFace_toEmbedding`). -/
theorem exists_eq_chartEmbedding {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    (h : P.IsLegal ∨ Q.IsLegal) (φ : P.Chart ↪[hullLanguage.{u} α] Q.Chart) :
    ∃ (e : Fin k ↪ Fin k') (he : restrictFace e Q = some P), φ = chartEmbedding he :=
  ⟨_, restrictFace_toEmbedding h φ, Embedding.ext fun _ ↦ rfl⟩

end StageType

end VaughtConjecture
