/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Realization.Basic

/-!
# Canonical finite hulls from consistency and covering

Roadmap, Layer 2 (derive canonical finite hulls from consistency and covering alone; actual finite
supports are precisely the finite closed sets; comparisons use these hulls where they only need a
containing chart); semantic contract, items 2 and 4; the expositions, §1 ("compute it inside any
containing chart; consistency and a common larger chart show that the answer is independent of
that choice").

The **support** of an occurrence `x` is the set of points of its tuple (`Occurrence.support`).
Inside `x`, a finite set `F ⊆ M` has coordinates `x.coords F` and a hull `x.hull F`: the image of
the hull of its coordinates in the plan of the type of `x` (`Geometry.hull`).  From exact
consistency and covering alone:

* every finite set lies in the support of an occurrence (`IsCovering.exists_subset_support`);
* the hull computed inside an occurrence does not depend on the occurrence
  (`Occurrence.hull_eq_hull`).  If the support of `x` lies in the support of `y`, then `x` is a
  face of `y` along some `f`.  Exact consistency, applied to this typed face, shows that the face
  is closed and that the type of `x` is the restriction of the type of `y` along `f`; here
  exactness matters, since consistency on visible faces alone would allow an invisible face to be
  typed.  Hulls in a restriction to a closed face are preimages of hulls
  (`StageType.hull_comap`, from `Geometry.hull_preimage`).  Two occurrences are compared inside
  a common larger occurrence, which exists by covering.

The **canonical finite hull** `R.finiteHull F` is the hull of `F` in any occurrence containing
it (`finiteHull_eq`).  It is a closure operator on finite sets (`Realization.hullClosure`), the
least support containing `F` (`finiteHull_subset_of_isSupport`); its closed sets
are exactly the supports of occurrences (`finiteHull_eq_self_iff`), and a tuple is typed exactly
when its support is such a support (`isSome_eval_iff_isSupport`).  Every hull is the hull of at
most two of its generators (`exists_subset_card_le_two_finiteHull_eq`), and the hull satisfies
anti-exchange (`finiteHull_antiExchange`), which reduces to anti-exchange at the closed hull of the
coordinates inside one occurrence (`Geometry.hull_insert_hull`).

A two-generator hull is not a two-point root.  The hull of two points is the support of an
occurrence generated by those two points, but it can have more than two points, and then the pair
itself is not closed (`finiteHull_eq_self_iff`), so that no tuple enumerating the pair is typed
(`isSome_eval_iff_isSupport`; the star plan of `VaughtConjecture.Geometry.Examples`).

## Placement

The geometry lemma `Geometry.hull_insert_hull` belongs in
`VaughtConjecture.Geometry.ConvexGeometry`, beside `Geometry.hull_restrict`, and
`Geometry.hull_preimage` in `VaughtConjecture.Geometry.Plan`, beside `Geometry.IsPlan.preimage`
(which has `Finset.preimage` and `Finset.map_preimage_eq_of_subset_range` in scope);
`StageType.isPlan`
in `VaughtConjecture.Stage.Basic` (or as `Scheme.IsWellFormed.isPlan` in
`VaughtConjecture.Stage.Scheme`, beside `Scheme.IsWellFormed.univ_mem_faces`); and the stage-type
corollary `StageType.hull_comap` of `Geometry.hull_preimage` in `VaughtConjecture.Stage.Basic`.
They are stated here so that those files are unchanged.
-/

universe u v

namespace VaughtConjecture

open Finset Geometry

/-! ### Hulls in an intersection-closed family -/

namespace Geometry

variable {α β : Type*} [DecidableEq α] [DecidableEq β] {A S : Finset α} {P : Finset (Finset α)}

/-- Adding a point to the hull of a set and closing gives the hull of the set with that point
added.  No hypothesis on the family is needed: a member of `P` containing `S` contains the hull
of `S`. -/
theorem hull_insert_hull (hS : S ⊆ A) (j : α) :
    hull A P (insert j (hull A P S)) = hull A P (insert j S) := by
  ext x
  simp only [mem_hull, insert_subset_iff]
  refine and_congr_right fun _ ↦ forall₂_congr fun B hB ↦ imp_congr_left ?_
  exact and_congr_right fun _ ↦ hull_subset_iff hB hS

/-- **Hulls in a pullback.**  Let `P` be intersection-closed and `f : β ↪ α` an embedding whose
range meets the ground set `A` in a member of `P`.  The hull of a subset `G` of the preimage of
`A` in the pullback of `P` along `f` (the sets whose image lies in `P`, on the preimage of `A`) is
the preimage of the hull of the image of `G`. -/
theorem hull_preimage (hinter : InfClosed (P : Set (Finset α))) {f : β ↪ α}
    (hf : (A.preimage f f.injective.injOn).map f ∈ P) {G : Finset β}
    (hG : G ⊆ A.preimage f f.injective.injOn) :
    hull (A.preimage f f.injective.injOn) (P.preimage (Finset.map f) (map_injective f).injOn) G =
      (hull A P (G.map f)).preimage f f.injective.injOn := by
  ext i
  simp only [mem_hull, mem_preimage]
  refine and_congr_right fun _ ↦
    ⟨fun h C hC hGC ↦ ?_, fun h D hD hGD ↦ (mem_map' f).mp (h _ hD (map_subset_map.mpr hGD))⟩
  set B := (A.preimage f f.injective.injOn).map f
  have hD : ((C ∩ B).preimage f f.injective.injOn).map f ∈ P := by
    rw [map_preimage_eq_of_subset_range fun a ha ↦ ?_]
    · exact mem_coe.mp (hinter (mem_coe.mpr hC) (mem_coe.mpr hf))
    · obtain ⟨b, -, rfl⟩ := mem_map.mp (mem_inter.mp (mem_coe.mp ha)).2
      exact ⟨b, rfl⟩
  have hGD : G ⊆ (C ∩ B).preimage f f.injective.injOn := fun g hg ↦
    mem_preimage.mpr (mem_inter.mpr ⟨hGC (mem_map_of_mem f hg), mem_map_of_mem f (hG hg)⟩)
  exact (mem_inter.mp (mem_preimage.mp (h _ hD hGD))).1

end Geometry

/-! ### Hulls in a stage type -/

namespace StageType

variable {α : Ordinal.{u}} {n m : ℕ}

/-- The faces of a stage type form a plan on all of its points. -/
theorem isPlan (t : StageType.{u} α n) : IsPlan univ t.toCellScheme.faces :=
  t.isWellFormed.ground_eq ▸ t.isWellFormed.isWellFormed.isPlan

/-- **Hulls in a restriction.**  The hull of a set of points in the restriction of a stage type to
a closed face is the preimage of the hull of its image (`Geometry.hull_preimage`). -/
theorem hull_comap (t : StageType.{u} α n) (f : Fin m ↪ Fin n)
    (hf : univ.map f ∈ t.toCellScheme.faces) (G : Finset (Fin m)) :
    hull univ (t.comap f hf).toCellScheme.faces G =
      (hull univ t.toCellScheme.faces (G.map f)).preimage f f.injective.injOn := by
  have hfaces : (t.comap f hf).toCellScheme.faces =
      t.toCellScheme.faces.preimage (Finset.map f) (map_injective f).injOn := by
    ext C
    simp
  rw [hfaces, ← hull_preimage t.isPlan.infClosed (by rwa [preimage_univ]) (by simp),
    preimage_univ]

end StageType

namespace Realization

variable {α : Ordinal.{u}} {M : Type v} {m n : ℕ} {R : Realization.{u, v} α M}
  {F G S : Finset M}

/-! ### Supports, coordinates, and hulls inside an occurrence -/

namespace Occurrence

variable (x : R.Occurrence)

/-- The **support** of an occurrence: the points of its tuple. -/
def support : Finset M := univ.map x.tuple

/-- The points of the support are the points of the tuple. -/
@[simp] theorem mem_support {a : M} : a ∈ x.support ↔ ∃ i, x.tuple i = a := by
  simp [support]

/-- The **coordinates** of a finite set in an occurrence. -/
noncomputable def coords (F : Finset M) : Finset (Fin x.arity) :=
  F.preimage x.tuple x.tuple.injective.injOn

/-- A coordinate of `F` is an index whose point lies in `F`. -/
@[simp] theorem mem_coords {i : Fin x.arity} : i ∈ x.coords F ↔ x.tuple i ∈ F := mem_preimage

/-- The coordinates of an image of coordinates are those coordinates. -/
@[simp] theorem coords_map (C : Finset (Fin x.arity)) : x.coords (C.map x.tuple) = C :=
  preimage_map _ _

variable {x} in
/-- A set in the support is the image of its coordinates. -/
theorem map_coords (hF : F ⊆ x.support) : (x.coords F).map x.tuple = F :=
  map_preimage_eq_of_subset_range fun a ha ↦ by simpa using hF ha

/-- The **hull** of a finite set inside an occurrence: the image of the hull of its coordinates
in the plan of the type. -/
noncomputable def hull (F : Finset M) : Finset M :=
  (Geometry.hull univ x.type.toCellScheme.faces (x.coords F)).map x.tuple

/-- The coordinates of a hull inside an occurrence are the hull of the coordinates. -/
@[simp] theorem coords_hull (F : Finset M) :
    x.coords (x.hull F) = Geometry.hull univ x.type.toCellScheme.faces (x.coords F) :=
  coords_map _ _

/-- A hull inside an occurrence lies in its support. -/
theorem hull_subset_support (F : Finset M) : x.hull F ⊆ x.support :=
  map_subset_map.mpr (subset_univ _)

variable {x} in
/-- A set in the support lies in its hull. -/
theorem subset_hull (hF : F ⊆ x.support) : F ⊆ x.hull F := by
  conv_lhs => rw [← map_coords hF]
  exact map_subset_map.mpr (Geometry.subset_hull (subset_univ _))

/-- Hulls inside an occurrence are monotone. -/
theorem hull_mono (hFG : F ⊆ G) : x.hull F ⊆ x.hull G :=
  map_subset_map.mpr (Geometry.hull_mono (monotone_preimage x.tuple.injective hFG))

/-- Hulls inside an occurrence are idempotent. -/
@[simp] theorem hull_hull (F : Finset M) : x.hull (x.hull F) = x.hull F := by
  rw [hull, coords_hull, hull_eq_self x.type.isPlan.isConvexGeometry.hull_mem (subset_univ _),
    hull]

/-- The hull of the support of an occurrence is its support. -/
@[simp] theorem hull_support : x.hull x.support = x.support := by
  rw [hull, support, coords_map, hull_eq_self x.type.isPlan.ground_mem Subset.rfl]

/-- A tuple whose points lie in the support of an occurrence is a face of its tuple. -/
theorem exists_trans_eq {t : Fin n ↪ M} (ht : univ.map t ⊆ x.support) :
    ∃ f : Fin n ↪ Fin x.arity, f.trans x.tuple = t := by
  have h (i : Fin n) : ∃ j, x.tuple j = t i := (x.mem_support).mp (ht (mem_map_of_mem t (by simp)))
  choose f hf using h
  exact ⟨⟨f, fun i j hij ↦ t.injective (by rw [← hf, ← hf, hij])⟩, Function.Embedding.ext hf⟩

/-- The image of a closed face of an occurrence is the support of an occurrence, a face. -/
theorem exists_support_eq_map (hR : R.IsConsistent) {C : Finset (Fin x.arity)}
    (hC : C ∈ x.type.toCellScheme.faces) : ∃ y : R.Occurrence, y.support = C.map x.tuple := by
  refine ⟨x.face hR (C.orderEmbOfFin rfl).toEmbedding (by rwa [map_orderEmbOfFin_univ]), ?_⟩
  -- `Fin (x.face ..).arity` is definitionally `Fin #C`, but `rw` cannot see through the dependent
  -- `arity` field, so the support is unfolded by `change`.
  change univ.map ((C.orderEmbOfFin rfl).toEmbedding.trans x.tuple) = C.map x.tuple
  rw [← map_map, map_orderEmbOfFin_univ]

/-- A hull inside an occurrence is the support of an occurrence. -/
theorem exists_support_eq_hull (hR : R.IsConsistent) (F : Finset M) :
    ∃ y : R.Occurrence, y.support = x.hull F :=
  x.exists_support_eq_map hR x.type.isPlan.isConvexGeometry.hull_mem

end Occurrence

/-- Under covering, every finite set lies in the support of an occurrence. -/
theorem IsCovering.exists_subset_support (hc : R.IsCovering) (F : Finset M) :
    ∃ x : R.Occurrence, F ⊆ x.support := by
  obtain ⟨m, u, f, hf, hu⟩ :=
    hc (F.equivFin.symm.toEmbedding.trans (Function.Embedding.subtype (· ∈ F)))
  obtain ⟨p, hp⟩ := Option.isSome_iff_exists.mp hu
  refine ⟨⟨m, u, p, hp⟩, fun a ha ↦ Occurrence.mem_support _ |>.mpr ⟨f (F.equivFin ⟨a, ha⟩), ?_⟩⟩
  simpa using DFunLike.congr_fun hf (F.equivFin ⟨a, ha⟩)

namespace Occurrence

variable {x : R.Occurrence}

/-- **Hulls in a larger occurrence.**  If the support of `x` lies in the support of `y`, then a
set in the support of `x` has the same hull inside `x` and inside `y`.  The type of `x` is the
restriction of the type of `y` to a closed face, by exact consistency. -/
theorem hull_eq_of_support_subset (hR : R.IsConsistent) {y : R.Occurrence}
    (hxy : x.support ⊆ y.support) (hF : F ⊆ x.support) : x.hull F = y.hull F := by
  obtain ⟨f, hf⟩ := y.exists_trans_eq hxy
  obtain ⟨hfc, hx⟩ := (StageType.restrictFace_eq_some_iff _ _).mp
    (restrictFace_eq_of_eval hR y.eval_tuple f (hf ▸ x.eval_tuple))
  have hfi (i : Fin x.arity) : y.tuple (f i) = x.tuple i := DFunLike.congr_fun hf i
  have hcoords : (x.coords F).map f = y.coords F := by
    ext j
    simp only [mem_map, mem_coords]
    refine ⟨fun ⟨i, hi, hij⟩ ↦ by rwa [← hij, hfi], fun hj ↦ ?_⟩
    obtain ⟨i, hi⟩ := x.mem_support.mp (hF hj)
    exact ⟨i, hi ▸ hj, y.tuple.injective (by rw [hfi, hi])⟩
  have hsub : Geometry.hull univ y.type.toCellScheme.faces (y.coords F) ⊆ univ.map f :=
    Geometry.hull_subset hfc (hcoords ▸ map_subset_map.mpr (subset_univ _))
  rw [hull, hull, ← hx, StageType.hull_comap, hcoords, ← hf, ← map_map,
    map_preimage_eq_of_subset_range fun a ha ↦ by simpa using hsub (mem_coe.mp ha)]

/-- **Independence of the containing occurrence.**  Under exact consistency and covering, a
finite set has the same hull inside any two occurrences containing it: both are compared inside
a common larger occurrence. -/
theorem hull_eq_hull (hR : R.IsConsistent) (hc : R.IsCovering) {y : R.Occurrence}
    (hx : F ⊆ x.support) (hy : F ⊆ y.support) : x.hull F = y.hull F := by
  classical
  obtain ⟨z, hz⟩ := hc.exists_subset_support (x.support ∪ y.support)
  rw [hull_eq_of_support_subset hR (subset_union_left.trans hz) hx,
    hull_eq_of_support_subset hR (subset_union_right.trans hz) hy]

end Occurrence

/-! ### The canonical finite hull -/

open Classical in
/-- The **canonical finite hull** of a finite set: its hull inside a chosen occurrence containing
it, or the set itself if there is none.  Under exact consistency and covering the hull does not
depend on the containing occurrence (`finiteHull_eq`). -/
noncomputable def finiteHull (R : Realization.{u, v} α M) (F : Finset M) : Finset M :=
  if h : ∃ x : R.Occurrence, F ⊆ x.support then h.choose.hull F else F

/-- **The canonical hull is computed inside any containing occurrence.** -/
theorem finiteHull_eq (hR : R.IsConsistent) (hc : R.IsCovering) (x : R.Occurrence)
    (hF : F ⊆ x.support) : R.finiteHull F = x.hull F := by
  unfold finiteHull
  split_ifs with h
  · exact h.choose.hull_eq_hull hR hc h.choose_spec hF
  · exact absurd ⟨x, hF⟩ h

/-- A finite set lies in its canonical hull. -/
theorem subset_finiteHull (F : Finset M) : F ⊆ R.finiteHull F := by
  unfold finiteHull
  split_ifs with h
  · exact Occurrence.subset_hull h.choose_spec
  · exact Subset.rfl

/-- The canonical hull is monotone. -/
theorem finiteHull_mono (hR : R.IsConsistent) (hc : R.IsCovering) :
    Monotone R.finiteHull := fun F G hFG ↦ by
  obtain ⟨x, hx⟩ := hc.exists_subset_support G
  rw [finiteHull_eq hR hc x hx, finiteHull_eq hR hc x (hFG.trans hx)]
  exact x.hull_mono hFG

/-- The canonical hull is idempotent. -/
@[simp] theorem finiteHull_finiteHull (hR : R.IsConsistent) (hc : R.IsCovering)
    (F : Finset M) : R.finiteHull (R.finiteHull F) = R.finiteHull F := by
  obtain ⟨x, hx⟩ := hc.exists_subset_support F
  rw [finiteHull_eq hR hc x hx, finiteHull_eq hR hc x (x.hull_subset_support F), x.hull_hull]

/-- The canonical finite hull as a **closure operator** on the finite sets of the carrier. -/
noncomputable def hullClosure (hR : R.IsConsistent) (hc : R.IsCovering) :
    ClosureOperator (Finset M) :=
  .mk' R.finiteHull (finiteHull_mono hR hc) subset_finiteHull
    fun F ↦ (finiteHull_finiteHull hR hc F).le

/-- The hull closure is the canonical finite hull. -/
@[simp] theorem hullClosure_apply (hR : R.IsConsistent) (hc : R.IsCovering) (F : Finset M) :
    R.hullClosure hR hc F = R.finiteHull F := rfl

/-! ### Supports of occurrences are the closed finite sets -/

variable (R) in
/-- A finite set is a **support** in `R` if it is the support of an occurrence. -/
def IsSupport (S : Finset M) : Prop := ∃ x : R.Occurrence, x.support = S

/-- The support of an occurrence is a support. -/
theorem Occurrence.isSupport (x : R.Occurrence) : R.IsSupport x.support := ⟨x, rfl⟩

/-- Every canonical hull is a support. -/
theorem isSupport_finiteHull (hR : R.IsConsistent) (hc : R.IsCovering) (F : Finset M) :
    R.IsSupport (R.finiteHull F) := by
  obtain ⟨x, hx⟩ := hc.exists_subset_support F
  rw [finiteHull_eq hR hc x hx]
  exact x.exists_support_eq_hull hR F

/-- **The closed finite sets are the supports**: a finite set is its own canonical hull exactly
when it is the support of an occurrence. -/
theorem finiteHull_eq_self_iff (hR : R.IsConsistent) (hc : R.IsCovering) :
    R.finiteHull S = S ↔ R.IsSupport S := by
  refine ⟨fun h ↦ h ▸ isSupport_finiteHull hR hc S, ?_⟩
  rintro ⟨x, rfl⟩
  rw [finiteHull_eq hR hc x Subset.rfl, x.hull_support]

/-- **Minimality**: the canonical hull of `F` lies in every support containing `F`. -/
theorem finiteHull_subset_of_isSupport (hR : R.IsConsistent) (hc : R.IsCovering)
    (hS : R.IsSupport S) (hFS : F ⊆ S) : R.finiteHull F ⊆ S :=
  (finiteHull_mono hR hc hFS).trans ((finiteHull_eq_self_iff hR hc).mpr hS).le

/-- The canonical hull of `F` lies in a support exactly when `F` does. -/
theorem finiteHull_subset_iff (hR : R.IsConsistent) (hc : R.IsCovering) (hS : R.IsSupport S) :
    R.finiteHull F ⊆ S ↔ F ⊆ S :=
  ⟨(subset_finiteHull F).trans, finiteHull_subset_of_isSupport hR hc hS⟩

/-- **Typed tuples are the enumerations of supports**: under exact consistency, a tuple is typed
exactly when its set of points is the support of an occurrence. -/
theorem isSome_eval_iff_isSupport (hR : R.IsConsistent) (t : Fin n ↪ M) :
    (R.eval t).isSome ↔ R.IsSupport (univ.map t) := by
  refine ⟨fun h ↦ ?_, fun ⟨x, hx⟩ ↦ ?_⟩
  · obtain ⟨p, hp⟩ := Option.isSome_iff_exists.mp h
    exact ⟨⟨n, t, p, hp⟩, rfl⟩
  obtain ⟨f, rfl⟩ := x.exists_trans_eq hx.ge
  have hf : univ.map f = univ := map_injective x.tuple (by rw [map_map, ← hx, Occurrence.support])
  rw [isSome_eval_face_iff hR, hf]
  exact x.type.isPlan.ground_mem

/-! ### Two generators and anti-exchange -/

/-- **Two generators**: the canonical hull of a finite set is the canonical hull of at most two
of its points.  The hull itself can be large. -/
theorem exists_subset_card_le_two_finiteHull_eq (hR : R.IsConsistent) (hc : R.IsCovering)
    (F : Finset M) : ∃ T ⊆ F, #T ≤ 2 ∧ R.finiteHull T = R.finiteHull F := by
  obtain ⟨x, hx⟩ := hc.exists_subset_support F
  obtain ⟨C, hCF, hC2, hCeq⟩ :=
    x.type.isPlan.exists_subset_card_le_two_hull_eq (subset_univ (x.coords F))
  refine ⟨C.map x.tuple, ?_, (card_map _).symm ▸ hC2, ?_⟩
  · conv_rhs => rw [← Occurrence.map_coords hx]
    exact map_subset_map.mpr hCF
  · rw [finiteHull_eq hR hc x (map_subset_map.mpr (subset_univ _)), finiteHull_eq hR hc x hx,
      Occurrence.hull, Occurrence.hull, Occurrence.coords_map, hCeq]

/-- **Anti-exchange** for the canonical hull: if `a ≠ b`, `a` is not in the hull of `S`, and `a`
is in the hull of `S` with `b` added, then `b` is not in the hull of `S` with `a` added. -/
theorem finiteHull_antiExchange [DecidableEq M] (hR : R.IsConsistent) (hc : R.IsCovering)
    (S : Finset M) {a b : M} (hab : a ≠ b) (ha : a ∉ R.finiteHull S)
    (hb : a ∈ R.finiteHull (insert b S)) : b ∉ R.finiteHull (insert a S) := by
  obtain ⟨x, hx⟩ := hc.exists_subset_support (insert a (insert b S))
  have hbS : insert b S ⊆ x.support := (subset_insert _ _).trans hx
  have hS : S ⊆ x.support := (subset_insert _ _).trans hbS
  rw [finiteHull_eq hR hc x hS] at ha
  rw [finiteHull_eq hR hc x hbS] at hb
  rw [finiteHull_eq hR hc x (insert_subset (hx (mem_insert_self _ _)) hS)]
  obtain ⟨i, rfl⟩ := x.mem_support.mp (hx (mem_insert_self _ _))
  obtain ⟨j, rfl⟩ := x.mem_support.mp (hbS (mem_insert_self _ _))
  have hcoords (k : Fin x.arity) : x.coords (insert (x.tuple k) S) = insert k (x.coords S) := by
    ext
    simp [x.tuple.injective.eq_iff]
  have hG := x.type.isPlan.isConvexGeometry
  simp only [Occurrence.hull, mem_map', hcoords] at ha hb ⊢
  rw [← hull_insert_hull (subset_univ _)] at hb ⊢
  exact hG.antiExchange hG.hull_mem (fun h ↦ hab (congrArg x.tuple h)) ha hb

end Realization

end VaughtConjecture
