/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Language.HullDefinability

/-!
# The two-charts theorem and canonical hull operations on realizations

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures", items 2 and 3);
`HULL_ALGEBRA.md`, §§1–3 and 5; semantic contract, item 10 (uniqueness of the charts that witness
a hull operation, for every pair; preservation by embeddings proved from those charts).

These are the statements of `VaughtConjecture.Language.HullOperations` about finite charts, read
on an arbitrary realization `R` that is exactly consistent (`Realization.IsConsistent`) and
covering (`Realization.IsCovering`).  This is what "exactly consistent covering realization" means
in the roadmap; no legality of the actual types is assumed unless a statement says so.

**The two-charts theorem** (`Realization.eq_of_eval_eq_some`, `HULL_ALGEBRA.md`, §1).  Two
occurrences `g`, `g'` of a type `q` generated by the coordinates `i₀`, `i₁` that agree at `i₀` and
`i₁` are equal.  The proof uses each law once:

* covering (`IsCovering.exists_subset_support`, applied to the points of `g` and `g'`) supplies a
  common occurrence `x` containing both, so that `g` and `g'` are faces of the tuple of `x`
  along face maps `f` and `f'` (`Occurrence.exists_trans_eq`);
* exact consistency at the occurrence `x` (`restrictFace_eq_of_eval`) shows that the type of `x`
  restricts along `f` and along `f'` literally to `q`.  The face is typed, so it is a closed face
  of the type of `x`: this uses the clause that an invisible face of a typed tuple is untyped;
  consistency on visible faces alone would allow a typed face of the tuple of `x` whose points
  do not form a closed face of the type of `x`;
* the two-charts theorem for finite charts (`StageType.eq_of_restrictFace_eq_some`), inside the
  type of `x`, gives `f = f'`.

Moreover, the points of an occurrence of a two-generated type are the canonical hull of its
two generators (`Realization.map_univ_eq_finiteHull_of_eval`), so it lies in every occurrence
containing them (`Realization.map_univ_subset_support_of_eval`).

**Canonical hull operations.**  Consequently `Realization.hullOp`, defined by a choice, is
canonical: where there is a chart witness, its value is the target point of any chart witness
(`Realization.hullOp_eq_of_eval`), and the default value, the first argument, is taken exactly
where there is none.  The hull operations are **total** in the sense of roadmap, Layer 2, item 2:
at every pair `a`, `b`, the pairs with `a = b` and the pairs that do not span a closed face
included, exactly one point `y` satisfies the defining relation "some chart witness at `a`, `b`
has target `y`, or there is no chart witness and `y = a`", and it is the value of the hull
operation (`Realization.hullOp_eq_iff`, `Realization.existsUnique_chartWitness_or_default`).
Totality needs exact consistency and covering only: neither legality nor a chart in which the pair
is a face.  The value lies in the hull of `{a, b}` inside every occurrence containing `a` and `b`
(`Realization.hullOp_mem_hull`), hence in the canonical finite hull
(`Realization.hullOp_mem_finiteHull`, `HULL_ALGEBRA.md`, §2), and for `a ≠ b` every point of that
hull is the value of a hull operation at `a`, `b`, provided the type of the occurrence on the hull
is legal (`Realization.exists_hullOp_eq_of_mem_finiteHull`, §3).  That legality is essential: it
holds whenever some hull operation at `a`, `b` returns `b`
(`Realization.isLegal_of_hullOp_eq_right`).  With legal types, the canonical finite hull of a pair
of distinct points is the set of values of the hull operations at it
(`Realization.mem_finiteHull_pair_iff`).

**Definability.**  With the graph formula `HullIndex.graphFormula` of
`VaughtConjecture.Language.HullDefinability`, `Realization.hullOp_eq_iff` is the first-order
definability of the hull operations on every exactly consistent covering realization (roadmap,
Layer 2, item 2): the graph formula holds at `(a, b, y)` exactly when `y` is the value of the hull
operation at `a` and `b` (`Realization.realize_graphFormula_iff`), so each hull operation is a
parameter-free definable function of the stage chart language (`Realization.definableFun_hullOp`).
No legality is needed.

**Embeddings.**  An **embedding of realizations** `φ : R.Embedding S` (`Realization.Embedding`)
is an injective map of carriers that carries every actual occurrence to an actual occurrence with
the same type; nothing is required of untyped tuples.  The embeddings of `HULL_ALGEBRA.md`, §5,
injective maps preserving the evaluation of every tuple (carrying actual charts to actual charts
of the same type, and no other tuple to an actual chart), are embeddings of realizations
(`Realization.Embedding.ofEvalTrans`).  Conversely, when `R` and `S` are exactly consistent and
`R` is covering, an embedding of realizations preserves the evaluation of every tuple
(`Realization.Embedding.eval_trans`), so it is an embedding in the sense of §5
(`Realization.Embedding.eq_ofEvalTrans`) and an embedding of the structures in the stage chart
language (`Realization.Embedding.toChartEmbedding`).  An embedding of the structures in the stage
chart language is an embedding of realizations when the types of `R` are legal
(`Realization.Embedding.ofChartEmbedding`), since the language has relation symbols only for legal
types.

Between exactly consistent covering realizations, an embedding of realizations commutes with
every hull operation, the default value included (`Realization.Embedding.hullOp_map`): the image
of a chart witness is a chart witness, and a chart witness in `S` at `φ a`, `φ b` has as points
the canonical hull of `{φ a, φ b}`, which lies in the image of an occurrence of `R` containing `a`
and `b`, so it reflects to a chart witness in `R`.  Hence an embedding of realizations is an
embedding of the structures in the hull language (`Realization.Embedding.toHullEmbedding`).  So
roadmap, Layer 2, item 3 is proved here for embeddings of realizations, hence for the embeddings
of §5, and for an arbitrary embedding of the structures in the stage chart language only when the
types of the source are legal (through `Realization.Embedding.ofChartEmbedding`); the general case
of the latter is not proved here.  Isomorphisms of realizations are embeddings
(`Realization.Iso.toEmbedding`), so hull operations are invariant under isomorphism
(`Realization.Iso.hullOp_map`).

**Face realizations.**  The face realization of a chart is exactly consistent and covering
(`StageType.isConsistent_faceRealization`, `StageType.isCovering_faceRealization`), and a face map
along which the restriction is literal is an embedding of face realizations
(`StageType.faceRealizationEmbedding`).  On face realizations the statements here specialize to
`StageType.eq_of_restrictFace_eq_some`, `StageType.hullOp_eq_of_restrictFace`, and
`StageType.hullOp_map_of_restrictFace` (`VaughtConjecture.Realization.TwoChartsExamples`).

## Placement

This file belongs to Layer 2 of `roadmap/README.md`.
-/

universe u v w

namespace VaughtConjecture

open Finset FirstOrder

namespace Realization

variable {α : Ordinal.{u}} {M : Type v} {N : Type w} {m n : ℕ} {R : Realization.{u, v} α M}

/-! ### Two-generated occurrences -/

namespace Occurrence

variable [DecidableEq M] (x : R.Occurrence)

/-- The two points of an occurrence at two coordinates lie in its support. -/
theorem pair_subset_support (i j : Fin x.arity) : {x.tuple i, x.tuple j} ⊆ x.support :=
  insert_subset_iff.mpr ⟨x.mem_support.mpr ⟨i, rfl⟩,
    singleton_subset_iff.mpr (x.mem_support.mpr ⟨j, rfl⟩)⟩

/-- The coordinates of the points of an occurrence at two coordinates are those coordinates. -/
@[simp] theorem coords_pair (i j : Fin x.arity) : x.coords {x.tuple i, x.tuple j} = {i, j} := by
  ext k
  simp [x.tuple.injective.eq_iff]

/-- **The support of a two-generated occurrence** is the hull, inside the occurrence, of the
points at its two generating coordinates. -/
theorem hull_pair_eq_support {i₀ i₁ : Fin x.arity}
    (hgen : Geometry.hull univ x.type.toCellScheme.faces {i₀, i₁} = univ) :
    x.hull {x.tuple i₀, x.tuple i₁} = x.support := by
  rw [hull, coords_pair, hgen, support]

end Occurrence

section TwoCharts

variable {q : StageType.{u} α m} {i₀ i₁ : Fin m}

/-- **The points of an occurrence of a two-generated type** are the canonical finite hull of the
points at its two generators (`HULL_ALGEBRA.md`, §2), the realization-level form of
`StageType.map_univ_eq_hull_of_restrictFace`. -/
theorem map_univ_eq_finiteHull_of_eval [DecidableEq M] (hR : R.IsConsistent)
    (hc : R.IsCovering) (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ)
    {g : Fin m ↪ M} (hg : R.eval g = some q) : univ.map g = R.finiteHull {g i₀, g i₁} := by
  let y : R.Occurrence := ⟨m, g, q, hg⟩
  rw [finiteHull_eq hR hc y (y.pair_subset_support i₀ i₁)]
  exact (y.hull_pair_eq_support hgen).symm

/-- An occurrence of a two-generated type lies in every occurrence containing the points at its
two generators. -/
theorem map_univ_subset_support_of_eval [DecidableEq M] (hR : R.IsConsistent)
    (hc : R.IsCovering) (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ)
    {g : Fin m ↪ M} (hg : R.eval g = some q) (x : R.Occurrence)
    (hx : {g i₀, g i₁} ⊆ x.support) : univ.map g ⊆ x.support := by
  rw [map_univ_eq_finiteHull_of_eval hR hc hgen hg, finiteHull_eq hR hc x hx]
  exact x.hull_subset_support _

/-- **The two-charts theorem** for exactly consistent covering realizations (`HULL_ALGEBRA.md`,
§1): two occurrences `g`, `g'` of a type `q` generated by the coordinates `i₀`, `i₁` that agree at
`i₀` and `i₁` are equal.

Covering supplies an occurrence `x` containing the points of both; `g` and `g'` are faces of the
tuple of `x`, and exact consistency at `x` shows that the type of `x` restricts along both face
maps literally to `q` (the faces are typed, so they are closed faces of the type of `x`); the
two-charts theorem for finite charts, `StageType.eq_of_restrictFace_eq_some`, applies inside that
type.  No legality is assumed.  The generators may coincide (then `q` has at most one point). -/
theorem eq_of_eval_eq_some (hR : R.IsConsistent) (hc : R.IsCovering)
    (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ) {g g' : Fin m ↪ M}
    (hg : R.eval g = some q) (hg' : R.eval g' = some q) (h₀ : g i₀ = g' i₀) (h₁ : g i₁ = g' i₁) :
    g = g' := by
  classical
  -- covering: a common occurrence containing the points of `g` and `g'`
  obtain ⟨x, hx⟩ := hc.exists_subset_support (univ.map g ∪ univ.map g')
  obtain ⟨f, rfl⟩ := x.exists_trans_eq (subset_union_left.trans hx)
  obtain ⟨f', rfl⟩ := x.exists_trans_eq (subset_union_right.trans hx)
  -- exact consistency at `x`: both are faces of `x` with the literal restriction `q`
  have hf := restrictFace_eq_of_eval hR x.eval_tuple f hg
  have hf' := restrictFace_eq_of_eval hR x.eval_tuple f' hg'
  -- the two-charts theorem inside the type of `x`
  rw [StageType.eq_of_restrictFace_eq_some hgen hf hf' (x.tuple.injective h₀)
    (x.tuple.injective h₁)]

end TwoCharts

/-! ### Canonical hull operations -/

section HullOp

variable {ι : HullIndex.{u} α}

/-- **The hull operation is canonical**: at the points of a chart witness at the generators, the
hull operation is the point of that chart witness at the target, whichever chart witness
`Realization.hullOp` chooses (the two-charts theorem).  No legality is assumed beyond that of the
type of the hull index, which the proof does not use. -/
theorem hullOp_eq_of_eval (hR : R.IsConsistent) (hc : R.IsCovering) {g : Fin ι.arity ↪ M}
    (hg : R.eval g = some ι.type) : R.hullOp ι (g ι.left) (g ι.right) = g ι.target := by
  obtain ⟨g', hg', h₀, h₁, he⟩ := hullOp_spec ⟨g, hg, rfl, rfl⟩
  rw [he, eq_of_eval_eq_some hR hc ι.hull_eq_univ hg' hg h₀ h₁]

/-- **The defining relation of a hull operation** (`HULL_ALGEBRA.md`, §1): on an exactly
consistent covering realization, the value of a hull operation at `a` and `b` is `y` exactly when
some chart witness at `a` and `b` has the target point `y`, or there is no chart witness and `y` is
the default value `a`.  The direction from left to right holds in every realization; the converse
is the two-charts theorem. -/
theorem hullOp_eq_iff (hR : R.IsConsistent) (hc : R.IsCovering) (ι : HullIndex.{u} α)
    (a b y : M) :
    R.hullOp ι a b = y ↔
      (∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b ∧
        g ι.target = y) ∨
      ((¬ ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) ∧
        y = a) := by
  by_cases h : ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b
  · obtain ⟨g, hg, rfl, rfl⟩ := h
    rw [hullOp_eq_of_eval hR hc hg]
    refine ⟨fun hy ↦ Or.inl ⟨g, hg, rfl, rfl, hy⟩, ?_⟩
    rintro (⟨g', hg', h₀, h₁, rfl⟩ | ⟨hn, -⟩)
    · rw [eq_of_eval_eq_some hR hc ι.hull_eq_univ hg hg' h₀.symm h₁.symm]
    · exact absurd ⟨g, hg, rfl, rfl⟩ hn
  · rw [hullOp_of_not_exists h]
    refine ⟨fun hy ↦ Or.inr ⟨h, hy.symm⟩, ?_⟩
    rintro (⟨g, hg, h₀, h₁, -⟩ | ⟨-, rfl⟩)
    · exact absurd ⟨g, hg, h₀, h₁⟩ h
    · rfl

/-- **The hull operations are total** (roadmap, Layer 2, item 2): on an exactly consistent
covering realization, at every pair of points, equal or not, exactly one point satisfies the
defining relation of a hull operation, namely its value. -/
theorem existsUnique_chartWitness_or_default (hR : R.IsConsistent) (hc : R.IsCovering)
    (ι : HullIndex.{u} α) (a b : M) :
    ∃! y : M,
      (∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b ∧
        g ι.target = y) ∨
      ((¬ ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) ∧
        y = a) :=
  ⟨R.hullOp ι a b, (hullOp_eq_iff hR hc ι a b _).mp rfl,
    fun y hy ↦ ((hullOp_eq_iff hR hc ι a b y).mpr hy).symm⟩

variable [DecidableEq M]

/-- **Hull operations stay in the two-point hull, inside every containing occurrence**
(`HULL_ALGEBRA.md`, §2): the value of a hull operation at `a` and `b` lies in the hull of
`{a, b}` inside every occurrence containing `a` and `b`.  A chart witness has as points the hull
of its two generators, which does not depend on the containing occurrence. -/
theorem hullOp_mem_hull (hR : R.IsConsistent) (hc : R.IsCovering) (ι : HullIndex.{u} α)
    {a b : M} (x : R.Occurrence) (hx : {a, b} ⊆ x.support) : R.hullOp ι a b ∈ x.hull {a, b} := by
  by_cases h : ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b
  · obtain ⟨g, hg, rfl, rfl⟩ := h
    rw [hullOp_eq_of_eval hR hc hg, ← finiteHull_eq hR hc x hx,
      ← map_univ_eq_finiteHull_of_eval hR hc ι.hull_eq_univ hg]
    exact mem_map_of_mem g (mem_univ _)
  · rw [hullOp_of_not_exists h]
    exact Occurrence.subset_hull hx (mem_insert_self a _)

/-- **Hull operations stay in the two-point hull** (`HULL_ALGEBRA.md`, §2): the value of a hull
operation at `a` and `b` lies in the canonical finite hull of `{a, b}`. -/
theorem hullOp_mem_finiteHull (hR : R.IsConsistent) (hc : R.IsCovering) (ι : HullIndex.{u} α)
    (a b : M) : R.hullOp ι a b ∈ R.finiteHull {a, b} := by
  obtain ⟨x, hx⟩ := hc.exists_subset_support {a, b}
  rw [finiteHull_eq hR hc x hx]
  exact hullOp_mem_hull hR hc ι x hx

/-- **Legality along a two-point hull from a hull operation**: if `b` is the value at `a` and `b`
of a hull operation, with `a ≠ b`, then the occurrence on the canonical hull of `{a, b}` has a
legal type: the value is not the default, so it comes from a chart witness, whose points are that
hull and whose type is the legal type of the hull index. -/
theorem isLegal_of_hullOp_eq_right (hR : R.IsConsistent) (hc : R.IsCovering) {a b : M}
    (hab : a ≠ b) (hι : R.hullOp ι a b = b) (y : R.Occurrence)
    (hy : y.support = R.finiteHull {a, b}) : y.type.IsLegal := by
  by_cases h : ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b
  · obtain ⟨g, hg, rfl, rfl⟩ := h
    have hsub : univ.map y.tuple ⊆ univ.map g :=
      (hy.trans (map_univ_eq_finiteHull_of_eval hR hc ι.hull_eq_univ hg).symm).le
    let x : R.Occurrence := ⟨ι.arity, g, ι.type, hg⟩
    obtain ⟨f, hf⟩ := x.exists_trans_eq hsub
    refine ι.isLegal.restrictFace f (restrictFace_eq_of_eval hR hg f ?_)
    -- `x.tuple` is `g` by definition of `x`; the goal is restated with `x.tuple` so that
    -- `hf : f.trans x.tuple = y.tuple` applies.
    change R.eval (f.trans x.tuple) = some y.type
    rw [hf]
    exact y.eval_tuple
  · exact absurd ((hullOp_of_not_exists h).symm.trans hι) hab

/-- **Every point of a two-point hull is the value of a hull operation** (`HULL_ALGEBRA.md`, §3):
for distinct points `a`, `b`, every point of the canonical hull of `{a, b}` is the value at `a`
and `b` of the hull operation of the type of the occurrence on that hull, with its generators at
`a` and `b`.

Legality is assumed only of the occurrence on the hull of `{a, b}` (`hleg`), where it is needed
for that type to index a hull operation; it holds for every pair when `R` has legal types
(`mem_finiteHull_pair_iff`).  It is essential: if `b` is the value of a hull operation at `a` and
`b`, that type is legal (`isLegal_of_hullOp_eq_right`). -/
theorem exists_hullOp_eq_of_mem_finiteHull (hR : R.IsConsistent) (hc : R.IsCovering) {a b z : M}
    (hab : a ≠ b) (hleg : ∀ y : R.Occurrence, y.support = R.finiteHull {a, b} → y.type.IsLegal)
    (hz : z ∈ R.finiteHull {a, b}) : ∃ ι : HullIndex.{u} α, R.hullOp ι a b = z := by
  obtain ⟨y, hy⟩ := isSupport_finiteHull hR hc {a, b}
  have hsub : {a, b} ⊆ y.support := hy ▸ subset_finiteHull _
  obtain ⟨i₀, rfl⟩ := y.mem_support.mp (hsub (mem_insert_self _ _))
  obtain ⟨i₁, rfl⟩ := y.mem_support.mp (hsub (mem_insert_of_mem (mem_singleton_self _)))
  obtain ⟨j, rfl⟩ := y.mem_support.mp (hy ▸ hz)
  have hgen : Geometry.hull univ y.type.toCellScheme.faces {i₀, i₁} = univ := by
    have h := congrArg y.coords ((finiteHull_eq hR hc y hsub).symm.trans hy.symm)
    rwa [Occurrence.coords_hull, Occurrence.coords_pair, Occurrence.support,
      Occurrence.coords_map] at h
  let ι : HullIndex.{u} α := ⟨y.arity, y.type, hleg y hy, i₀, i₁, j,
    fun h ↦ hab (congrArg y.tuple h), hgen⟩
  exact ⟨ι, hullOp_eq_of_eval (ι := ι) hR hc y.eval_tuple⟩

/-- **The canonical hull of a pair is the set of values of the hull operations**
(`HULL_ALGEBRA.md`, (1) for a pair of distinct points): with legal types, a point lies in the
canonical finite hull of `{a, b}`, `a ≠ b`, exactly when it is the value at `a` and `b` of some
hull operation.  Legality is used only for the inclusion of the hull in the set of values
(`exists_hullOp_eq_of_mem_finiteHull`), where it is essential. -/
theorem mem_finiteHull_pair_iff (hR : R.IsConsistent) (hc : R.IsCovering) (hl : R.HasLegalTypes)
    {a b z : M} (hab : a ≠ b) :
    z ∈ R.finiteHull {a, b} ↔ ∃ ι : HullIndex.{u} α, R.hullOp ι a b = z :=
  ⟨exists_hullOp_eq_of_mem_finiteHull hR hc hab fun y _ ↦ hl _ _ y.eval_tuple,
    fun ⟨ι, h⟩ ↦ h ▸ hullOp_mem_finiteHull hR hc ι a b⟩

end HullOp

/-! ### Definability -/

section Definability

/-- **The graph of a hull operation is first-order definable** on every exactly consistent
covering realization (roadmap, Layer 2, item 2; `HULL_ALGEBRA.md`, §1): the graph formula holds at
`(a, b, y)` exactly when `y` is the value of the hull operation at `a` and `b`, the default value
included.  It is `hullOp_eq_iff` read through the meaning of the formulas
(`realize_chartWitnessFormula`, `realize_existsChartWitnessFormula`).  No legality is needed. -/
theorem realize_graphFormula_iff (hR : R.IsConsistent) (hc : R.IsCovering) (ι : HullIndex.{u} α)
    (a b y : M) :
    letI := R.toChartStructure
    ι.graphFormula.Realize ![a, b, y] ↔ R.hullOp ι a b = y := by
  let := R.toChartStructure
  rw [HullIndex.realize_graphFormula, realize_chartWitnessFormula,
    realize_existsChartWitnessFormula, hullOp_eq_iff hR hc]

/-- **The hull operations are parameter-free definable functions** of the stage chart language on
every exactly consistent covering realization, in the sense of Mathlib's `Set.DefinableFun`:
their graphs are defined by the graph formulas (`realize_graphFormula_iff`). -/
theorem definableFun_hullOp (hR : R.IsConsistent) (hc : R.IsCovering) (ι : HullIndex.{u} α) :
    letI := R.toChartStructure
    (∅ : Set M).DefinableFun (stageChartLanguage.{u} α)
      (fun v : Fin 2 → M ↦ R.hullOp ι (v 0) (v 1)) := by
  let := R.toChartStructure
  rw [Set.empty_definableFun_iff]
  refine ⟨ι.graphFormula.relabel ![some 0, some 1, none], Set.ext fun v ↦ ?_⟩
  have hv : v ∘ ![some 0, some 1, none] = ![v (some 0), v (some 1), v none] := by
    funext i
    match i with
    | 0 => rfl
    | 1 => rfl
    | 2 => rfl
  simp only [Function.tupleGraph, Set.mem_ofPred_eq, Language.Formula.realize_relabel, hv,
    realize_graphFormula_iff hR hc]
  rfl

end Definability

/-! ### Embeddings of realizations -/

/-- An **embedding of realizations** from `R` to `S`: an injective map of carriers carrying every
actual occurrence of `R` to an actual occurrence of `S` with the same type.  Nothing is required of
untyped tuples; between exactly consistent realizations with `R` covering, untyped tuples are
carried to untyped tuples (`Embedding.eval_trans`). -/
structure Embedding (R : Realization.{u, v} α M) (S : Realization.{u, w} α N) where
  /-- The injective map of carriers. -/
  toEmbedding : M ↪ N
  /-- Actual occurrences are carried to actual occurrences with the same type. -/
  eval_trans_of_eval ⦃n : ℕ⦄ (t : Fin n ↪ M) (p : StageType.{u} α n) :
    R.eval t = some p → S.eval (t.trans toEmbedding) = some p

namespace Embedding

variable {S : Realization.{u, w} α N}

instance : FunLike (R.Embedding S) M N where
  coe φ := φ.toEmbedding
  coe_injective φ ψ h := by
    obtain ⟨φ, _⟩ := φ
    obtain ⟨ψ, _⟩ := ψ
    congr
    exact DFunLike.coe_injective h

instance : EmbeddingLike (R.Embedding S) M N where
  injective' φ := φ.toEmbedding.injective

/-- The map of an embedding of realizations is its injective map of carriers. -/
@[simp] theorem coe_toEmbedding (φ : R.Embedding S) : ⇑φ.toEmbedding = φ :=
  rfl

/-- An embedding of realizations is injective. -/
protected theorem injective (φ : R.Embedding S) : Function.Injective φ :=
  φ.toEmbedding.injective

/-- The **image of an occurrence** under an embedding of realizations: the image tuple with the
same type. -/
def mapOccurrence (φ : R.Embedding S) (x : R.Occurrence) : S.Occurrence where
  arity := x.arity
  tuple := x.tuple.trans φ.toEmbedding
  type := x.type
  eval_tuple := φ.eval_trans_of_eval _ _ x.eval_tuple

/-- The support of the image of an occurrence is the image of its support. -/
@[simp] theorem support_mapOccurrence (φ : R.Embedding S) (x : R.Occurrence) :
    (φ.mapOccurrence x).support = x.support.map φ.toEmbedding :=
  (Finset.map_map _ _ _).symm

/-- **Untyped tuples are carried to untyped tuples**: if `R` and `S` are exactly consistent and
`R` is covering, an embedding of realizations preserves the evaluation of every tuple.  A tuple of
`R` is a face of a typed tuple `u` (covering); the image of `u` has the same type, and exact
consistency at `u` and at its image gives both faces the same restriction. -/
theorem eval_trans (hR : R.IsConsistent) (hc : R.IsCovering) (hS : S.IsConsistent)
    (φ : R.Embedding S) (t : Fin n ↪ M) : S.eval (t.trans φ.toEmbedding) = R.eval t := by
  obtain ⟨k, u, f, rfl, hu⟩ := hc t
  obtain ⟨p, hp⟩ := Option.isSome_iff_exists.mp hu
  rw [hR u p f hp, Function.Embedding.trans_assoc, hS _ p f (φ.eval_trans_of_eval u p hp)]

/-- **Relations are preserved and reflected**: when `R` and `S` are exactly consistent and `R` is
covering, an injective tuple of `R` has the type `p` exactly when its image has the type `p`; this
is the relation of `p` in the structures of the stage chart language (`toChartStructure`). -/
theorem exists_eval_comp_iff (hR : R.IsConsistent) (hc : R.IsCovering) (hS : S.IsConsistent)
    (φ : R.Embedding S) (xs : Fin n → M) (p : StageType.{u} α n) :
    (∃ h : Function.Injective (φ ∘ xs), S.eval ⟨φ ∘ xs, h⟩ = some p) ↔
      ∃ h : Function.Injective xs, R.eval ⟨xs, h⟩ = some p := by
  refine ⟨fun ⟨h, hq⟩ ↦ ⟨h.of_comp, ?_⟩, fun ⟨h, hq⟩ ↦ ⟨φ.injective.comp h, ?_⟩⟩
  · rw [← φ.eval_trans hR hc hS]
    exact hq
  · rw [← hq, ← φ.eval_trans hR hc hS ⟨xs, h⟩]
    rfl

/-- **Hull operations commute with embeddings of realizations, including the default value**
(roadmap, Layer 2, item 3; `HULL_ALGEBRA.md`, §5), between exactly consistent covering
realizations.  The image of a chart witness at `a`, `b` is a chart witness at `φ a`, `φ b`, and
the value in `S` is its target by the two-charts theorem in `S`.  Conversely a chart witness in
`S` at `φ a`, `φ b` has as points the canonical hull of `{φ a, φ b}` (exact consistency and
covering of `S`), which lies in the image of an occurrence of `R` containing `a` and `b` (covering
of `R`); so it is the image of a tuple of `R`, which has its type (`eval_trans`, by exact
consistency of `R`).  Hence the default value is taken in both or in neither.  No legality is
assumed. -/
theorem hullOp_map (hR : R.IsConsistent) (hcR : R.IsCovering) (hS : S.IsConsistent)
    (hcS : S.IsCovering) (φ : R.Embedding S) (ι : HullIndex.{u} α) (a b : M) :
    S.hullOp ι (φ a) (φ b) = φ (R.hullOp ι a b) := by
  classical
  by_cases h : ∃ w : Fin ι.arity ↪ M, R.eval w = some ι.type ∧ w ι.left = a ∧ w ι.right = b
  · obtain ⟨w, hw, rfl, rfl, hval⟩ := hullOp_spec h
    rw [hval]
    exact hullOp_eq_of_eval hS hcS (g := w.trans φ.toEmbedding) (φ.eval_trans_of_eval w _ hw)
  · rw [hullOp_of_not_exists h, hullOp_of_not_exists]
    rintro ⟨g, hg, hl, hr⟩
    obtain ⟨x, hx⟩ := hcR.exists_subset_support {a, b}
    have hpair : {g ι.left, g ι.right} ⊆ (φ.mapOccurrence x).support := by
      rw [hl, hr, support_mapOccurrence]
      intro c hc
      obtain ⟨d, hd, rfl⟩ : ∃ d ∈ ({a, b} : Finset M), φ d = c := by
        simp only [mem_insert, mem_singleton] at hc ⊢
        rcases hc with rfl | rfl
        exacts [⟨a, Or.inl rfl, rfl⟩, ⟨b, Or.inr rfl, rfl⟩]
      exact mem_map_of_mem _ (hx hd)
    obtain ⟨f, hf⟩ : ∃ f : Fin ι.arity ↪ Fin x.arity, f.trans (x.tuple.trans φ.toEmbedding) = g :=
      (φ.mapOccurrence x).exists_trans_eq
        (map_univ_subset_support_of_eval hS hcS ι.hull_eq_univ hg _ hpair)
    have hfg : (f.trans x.tuple).trans φ.toEmbedding = g := by
      rw [Function.Embedding.trans_assoc]
      exact hf
    refine h ⟨f.trans x.tuple, ?_, φ.injective ?_, φ.injective ?_⟩
    · rw [← φ.eval_trans hR hcR hS, hfg, hg]
    · exact (DFunLike.congr_fun hfg ι.left).trans hl
    · exact (DFunLike.congr_fun hfg ι.right).trans hr

/-- An **embedding of realizations is an embedding of the structures in the hull language**
between exactly consistent covering realizations: it preserves and reflects the relations
(`eval_trans`) and commutes with the hull operations (`hullOp_map`). -/
noncomputable def toHullEmbedding (hR : R.IsConsistent) (hcR : R.IsCovering)
    (hS : S.IsConsistent) (hcS : S.IsCovering) (φ : R.Embedding S) :
    letI := R.toHullStructure
    letI := S.toHullStructure
    M ↪[hullLanguage.{u} α] N :=
  letI := R.toHullStructure
  letI := S.toHullStructure
  { toEmbedding := φ.toEmbedding
    map_fun' := fun {n} f xs ↦ by
      induction f using hullLanguage.functions_induction with
      | op ι => exact (φ.hullOp_map hR hcR hS hcS ι (xs 0) (xs 1)).symm
    map_rel' := fun {n} r xs ↦ by
      rcases r with ⟨p, hp⟩ | r
      · -- the relation of `p` in the hull language is that of the stage chart language
        -- (`relMap_toHullStructure`), restated to apply `exists_eval_comp_iff`
        change (∃ h, S.eval ⟨φ ∘ xs, h⟩ = some p) ↔ ∃ h, R.eval ⟨xs, h⟩ = some p
        exact φ.exists_eval_comp_iff hR hcR hS xs p
      · exact (r : Empty).elim }

/-- The embedding of hull-language structures of an embedding of realizations has the map of the
embedding of realizations. -/
theorem toHullEmbedding_toEmbedding (hR : R.IsConsistent) (hcR : R.IsCovering)
    (hS : S.IsConsistent) (hcS : S.IsCovering) (φ : R.Embedding S) :
    letI := R.toHullStructure
    letI := S.toHullStructure
    (φ.toHullEmbedding hR hcR hS hcS).toEmbedding = φ.toEmbedding :=
  rfl

/-- An **embedding of realizations is an embedding of the structures in the stage chart
language** when `R` and `S` are exactly consistent and `R` is covering: it preserves and reflects
the relations (`exists_eval_comp_iff`). -/
def toChartEmbedding (hR : R.IsConsistent) (hc : R.IsCovering) (hS : S.IsConsistent)
    (φ : R.Embedding S) :
    letI := R.toChartStructure
    letI := S.toChartStructure
    M ↪[stageChartLanguage.{u} α] N :=
  letI := R.toChartStructure
  letI := S.toChartStructure
  { toEmbedding := φ.toEmbedding
    map_fun' := fun f _ ↦ (f : Empty).elim
    map_rel' := fun {n} r xs ↦ by
      -- the relation of a legal type `r.1` is `∃ h, eval ⟨xs, h⟩ = some r.1` by definition
      change (∃ h, S.eval ⟨φ ∘ xs, h⟩ = some r.1) ↔ ∃ h, R.eval ⟨xs, h⟩ = some r.1
      exact φ.exists_eval_comp_iff hR hc hS xs r.1 }

/-- The embedding of stage-chart-language structures of an embedding of realizations has the map
of the embedding of realizations. -/
theorem toChartEmbedding_toEmbedding (hR : R.IsConsistent) (hc : R.IsCovering)
    (hS : S.IsConsistent) (φ : R.Embedding S) :
    letI := R.toChartStructure
    letI := S.toChartStructure
    (φ.toChartEmbedding hR hc hS).toEmbedding = φ.toEmbedding :=
  rfl

/-- An **embedding in the sense of `HULL_ALGEBRA.md`, §5**, an injective map of carriers
preserving the evaluation of every tuple, is an embedding of realizations. -/
def ofEvalTrans (e : M ↪ N) (h : ∀ ⦃n : ℕ⦄ (t : Fin n ↪ M), S.eval (t.trans e) = R.eval t) :
    R.Embedding S where
  toEmbedding := e
  eval_trans_of_eval _ t _ ht := (h t).trans ht

/-- The map of the embedding of realizations of a map preserving evaluation is that map. -/
@[simp] theorem coe_ofEvalTrans (e : M ↪ N)
    (h : ∀ ⦃n : ℕ⦄ (t : Fin n ↪ M), S.eval (t.trans e) = R.eval t) : ⇑(ofEvalTrans e h) = e :=
  rfl

/-- **Embeddings of realizations are the embeddings of `HULL_ALGEBRA.md`, §5** when `R` and `S`
are exactly consistent and `R` is covering: every embedding of realizations preserves the
evaluation of every tuple (`eval_trans`) and is the embedding of its map. -/
theorem eq_ofEvalTrans (hR : R.IsConsistent) (hc : R.IsCovering) (hS : S.IsConsistent)
    (φ : R.Embedding S) : φ = ofEvalTrans φ.toEmbedding (fun _ t ↦ φ.eval_trans hR hc hS t) :=
  rfl

/-- An **embedding of the structures in the stage chart language** is an embedding of
realizations when the types of `R` are legal.  Legality is essential: the stage chart language has
relation symbols only for legal types, so an actual occurrence of `R` with a type that is not
legal is invisible to it. -/
def ofChartEmbedding (hl : R.HasLegalTypes)
    (φ : letI := R.toChartStructure
      letI := S.toChartStructure
      M ↪[stageChartLanguage.{u} α] N) : R.Embedding S :=
  letI := R.toChartStructure
  letI := S.toChartStructure
  { toEmbedding := φ.toEmbedding
    eval_trans_of_eval := fun _ t p ht ↦
      (S.relMap_toChartStructure p _ (t.trans φ.toEmbedding)).mp
        ((φ.map_rel (stageChartLanguage.symbol p (hl t p ht)) t).mpr
          ((R.relMap_toChartStructure p _ t).mpr ht)) }

end Embedding

/-- An **isomorphism of realizations is an embedding of realizations**. -/
def Iso.toEmbedding {S : Realization.{u, w} α N} (i : R.Iso S) : R.Embedding S where
  toEmbedding := i.1.toEmbedding
  eval_trans_of_eval n t p ht := by
    obtain ⟨e, rfl⟩ := i
    rw [map_eval_trans]
    exact ht

/-- **Hull operations are invariant under isomorphisms** of exactly consistent covering
realizations, the default value included. -/
theorem Iso.hullOp_map {S : Realization.{u, w} α N} (hR : R.IsConsistent) (hc : R.IsCovering)
    (i : R.Iso S) (ι : HullIndex.{u} α) (a b : M) :
    S.hullOp ι (i.1 a) (i.1 b) = i.1 (R.hullOp ι a b) := by
  obtain ⟨e, rfl⟩ := i
  exact Embedding.hullOp_map hR hc (hR.map e) (hc.map e) (Iso.toEmbedding ⟨e, rfl⟩) ι a b

end Realization

/-! ### Face realizations -/

namespace StageType

variable {α : Ordinal.{u}} {k k' : ℕ}

/-- A face map `e` along which the restriction of `Q` is `P` is an **embedding of face
realizations**, by the guarded composition law of face maps. -/
def faceRealizationEmbedding {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) :
    P.faceRealization.Embedding Q.faceRealization where
  toEmbedding := e
  eval_trans_of_eval _ t _ ht := by
    rw [faceRealization_eval, ← restrictFace_trans Q e t he]
    exact ht

/-- The embedding of face realizations of a face map is the face map. -/
@[simp] theorem faceRealizationEmbedding_apply {P : StageType.{u} α k} {Q : StageType.{u} α k'}
    {e : Fin k ↪ Fin k'} (he : restrictFace e Q = some P) (a : Fin k) :
    faceRealizationEmbedding he a = e a :=
  rfl

end StageType

end VaughtConjecture
