/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import VaughtConjecture.Geometry.IntervalPlan
import VaughtConjecture.Realization.TwoCharts

/-!
# Examples: the two-charts theorem and hull operations on realizations

Roadmap, Layer 2 ("Hull operations: finite charts as finite substructures", items 2 and 3);
`HULL_ALGEBRA.md`, §§1, 2 and 5; the hull-operation special cases listed under semantic contract,
item 11 (empty carriers, repeated inputs, and the default values).

* **Face realizations.**  On the face realization of a chart, which is exactly consistent and
  covering, the two-charts theorem, the canonical value of a hull operation, and the preservation
  of hull operations by embeddings specialize to the corresponding statements for finite charts:
  `StageType.eq_of_restrictFace_eq_some`, `StageType.hullOp_eq_of_restrictFace`, and
  `StageType.hullOp_map_of_restrictFace`.
* **Two occurrences containing the same pair** compute the same hull of the pair, and the value
  of every hull operation at the pair lies in both.
* **Definability.**  On face realizations the definability of the graph of a hull operation on
  realizations is `StageType.realize_graphFormula`, and the function symbols of the hull language
  are definable functions of the stage chart language on every exactly consistent covering
  realization.
* **The interval types.**  `interval n` is the stage type on `n` points with no cells whose faces
  are the intervals of `Fin n`.  It is the stage type `bare` of
  `VaughtConjecture.Language.HullOperationsExamples` for every number of points instead of three:
  `bare` is private to that module, and the examples here need four points as well.  On at
  least one point it is not legal (`not_isLegal_interval`, `not_isLegal_interval_three`).  The
  two-charts theorem does not need legality.  On three points it is generated by its end points
  `0` and `2`.
* **Two distinct charts containing the same pair in a consistent realization.**  In the face
  realization of `interval 4`, which is exactly consistent and covering, the whole chart and its
  face on `{0, 1, 2}` are distinct occurrences containing `0` and `1`, with the same hull of
  `{0, 1}`.
* **Exact consistency cannot be dropped.**  The realization `twoIntervals` on `Fin 4` gives the
  increasing enumerations of `{0, 1, 3}`, of `{0, 2, 3}`, and of all four points their interval
  types and no other tuple a type.  It is covering, and it has two different occurrences of the
  interval type on three points that agree at its end points; so it is not exactly consistent.
  It already fails consistency on visible faces (the visible face `{0, 1}` of `{0, 1, 3}` is
  untyped), so it does not isolate the clause on invisible faces.
* **The realization with no types** is exactly consistent but not covering, and every hull
  operation takes its default value there.
* **An empty carrier.**  The face realization of a stage type on no points is an exactly
  consistent covering realization on an empty carrier, in which the empty tuple is an occurrence.
* **Embeddings.**  Transport along a bijection preserves the evaluation of every tuple, so it is
  an embedding in the sense of `HULL_ALGEBRA.md`, §5, hence an embedding of realizations; the
  embedding of face realizations of a face map is an embedding of the structures in the stage
  chart language.
* **Repeated inputs.**  There is no chart witness at a repeated pair, so the defining relation of
  a hull operation has the default value as its only solution there, and embeddings preserve it.
  The two generators of a two-generated type may coincide, for a type on one point.
-/

universe u v w

namespace VaughtConjecture.Realization

open Finset

variable {α : Ordinal.{u}} {M : Type v} {N : Type w} {k k' m : ℕ}

/-! ### Face realizations -/

/-- On the face realization of a chart, the two-charts theorem is the two-charts theorem for finite
charts, `StageType.eq_of_restrictFace_eq_some`. -/
private example {P : StageType.{u} α k} {q : StageType.{u} α m} {i₀ i₁ : Fin m}
    (hgen : Geometry.hull univ q.toCellScheme.faces {i₀, i₁} = univ) {g g' : Fin m ↪ Fin k}
    (hg : StageType.restrictFace g P = some q) (hg' : StageType.restrictFace g' P = some q)
    (h₀ : g i₀ = g' i₀) (h₁ : g i₁ = g' i₁) : g = g' :=
  eq_of_eval_eq_some StageType.isConsistent_faceRealization StageType.isCovering_faceRealization
    hgen hg hg' h₀ h₁

/-- On the face realization of a chart, the canonical value of a hull operation is the value of
`StageType.hullOp_eq_of_restrictFace`. -/
private example {P : StageType.{u} α k} {ι : HullIndex.{u} α} {g : Fin ι.arity ↪ Fin k}
    (hg : StageType.restrictFace g P = some ι.type) :
    P.faceRealization.hullOp ι (g ι.left) (g ι.right) = g ι.target :=
  hullOp_eq_of_eval StageType.isConsistent_faceRealization StageType.isCovering_faceRealization hg

/-- On face realizations, preservation of hull operations by embeddings of realizations is
`StageType.hullOp_map_of_restrictFace`, the default value included. -/
private example {P : StageType.{u} α k} {Q : StageType.{u} α k'} {e : Fin k ↪ Fin k'}
    (he : StageType.restrictFace e Q = some P) (ι : HullIndex.{u} α) (a b : Fin k) :
    Q.faceRealization.hullOp ι (e a) (e b) = e (P.faceRealization.hullOp ι a b) :=
  (StageType.faceRealizationEmbedding he).hullOp_map StageType.isConsistent_faceRealization
    StageType.isCovering_faceRealization StageType.isConsistent_faceRealization
    StageType.isCovering_faceRealization ι a b

/-! ### Two occurrences containing the same pair -/

/-- Two occurrences containing the same pair compute the same hull of the pair, and the value of
every hull operation at the pair lies in both. -/
private example [DecidableEq M] {R : Realization.{u, v} α M} (hR : R.IsConsistent)
    (hc : R.IsCovering) (ι : HullIndex.{u} α) {a b : M} (x y : R.Occurrence)
    (hx : {a, b} ⊆ x.support) (hy : {a, b} ⊆ y.support) :
    x.hull {a, b} = y.hull {a, b} ∧ R.hullOp ι a b ∈ x.support ∩ y.support :=
  ⟨x.hull_eq_hull hR hc hx hy,
    mem_inter.mpr ⟨x.hull_subset_support _ (hullOp_mem_hull hR hc ι x hx),
      y.hull_subset_support _ (hullOp_mem_hull hR hc ι y hy)⟩⟩

/-- A witnessed value: at the points of an occurrence at the generators of its own legal
two-generated type, the hull operation of that type returns the point at the target. -/
private example {R : Realization.{u, v} α M} (hR : R.IsConsistent) (hc : R.IsCovering)
    (x : R.Occurrence) (hx : x.type.IsLegal) {i₀ i₁ j : Fin x.arity} (hne : i₀ ≠ i₁)
    (hgen : Geometry.hull univ x.type.toCellScheme.faces {i₀, i₁} = univ) :
    R.hullOp ⟨x.arity, x.type, hx, i₀, i₁, j, hne, hgen⟩ (x.tuple i₀) (x.tuple i₁) = x.tuple j :=
  hullOp_eq_of_eval hR hc x.eval_tuple

/-- Where there is no chart witness in the source, an embedding of exactly consistent covering
realizations carries the default value to the default value. -/
private example {R : Realization.{u, v} α M} {S : Realization.{u, w} α N} (hR : R.IsConsistent)
    (hcR : R.IsCovering) (hS : S.IsConsistent) (hcS : S.IsCovering) (φ : R.Embedding S)
    (ι : HullIndex.{u} α) {a b : M}
    (h : ¬ ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = b) :
    S.hullOp ι (φ a) (φ b) = φ a := by
  rw [φ.hullOp_map hR hcR hS hcS, hullOp_of_not_exists h]

/-! ### Definability on realizations -/

/-- On the face realization of a chart, the definability of the graph of a hull operation on
realizations is `StageType.realize_graphFormula`. -/
private example (P : StageType.{u} α k) (ι : HullIndex.{u} α) (a b z : Fin k) :
    ι.graphFormula.Realize ![P.toChart a, P.toChart b, P.toChart z] ↔
      P.faceRealization.hullOp ι a b = z :=
  P.faceRealization.realize_graphFormula_iff StageType.isConsistent_faceRealization
    StageType.isCovering_faceRealization ι a b z

/-- The function symbol of a hull index in the hull language is a definable function of the stage
chart language on every exactly consistent covering realization. -/
private example {R : Realization.{u, v} α M} (hR : R.IsConsistent) (hc : R.IsCovering)
    (ι : HullIndex.{u} α) :
    letI := R.toChartStructure
    (∅ : Set M).DefinableFun (stageChartLanguage.{u} α)
      (@FirstOrder.Language.Structure.funMap _ M R.toHullStructure 2 (hullLanguage.op ι)) :=
  definableFun_hullOp hR hc ι

/-! ### Embeddings -/

/-- Transport along a bijection preserves the evaluation of every tuple: it is an embedding in the
sense of `HULL_ALGEBRA.md`, §5, hence an embedding of realizations. -/
private example (R : Realization.{u, v} α M) (e : M ≃ N) : R.Embedding (R.map e) :=
  Embedding.ofEvalTrans e.toEmbedding fun _ t ↦ map_eval_trans R e t

/-- The embedding of face realizations of a face map is an embedding of the structures in the
stage chart language, with the face map as its map. -/
private example {P : StageType.{u} α k} {Q : StageType.{u} α k'} {e : Fin k ↪ Fin k'}
    (he : StageType.restrictFace e Q = some P) :
    letI := P.faceRealization.toChartStructure
    letI := Q.faceRealization.toChartStructure
    ((StageType.faceRealizationEmbedding he).toChartEmbedding
      StageType.isConsistent_faceRealization StageType.isCovering_faceRealization
      StageType.isConsistent_faceRealization).toEmbedding = e :=
  rfl

/-! ### The interval types -/

/-- The stage type on `n` points with no cells whose faces are the intervals of `Fin n`. -/
private def interval (n : ℕ) : StageType.{0} 0 n where
  card := 0
  toCellScheme := ⟨univ, Geometry.intervalPlan univ, Fin.elim0, Fin.elim0⟩
  rows := ⟨fun s ↦ s.elim0⟩
  label := Fin.elim0
  isWellFormed := ⟨rfl, ⟨inferInstance, Geometry.isPlan_intervalPlan _, fun d ↦ d.elim0⟩⟩
  isCoded s := s.elim0
  isLawful := CellScheme.Rows.isLawful_of_isEmpty _
  atStage d := d.elim0

/-- The interval type on at least one point is not legal: the graded face `({0}, 1)` is the graded
index of no cell. -/
private theorem not_isLegal_interval {n : ℕ} (hn : 0 < n) : ¬ (interval n).IsLegal := fun h ↦ by
  obtain ⟨d, -⟩ := h.isComplete ({⟨0, hn⟩}, 1)
    ⟨Geometry.mem_intervalPlan.mpr ⟨subset_univ _, fun x hx y hy z _ hxz hzy ↦ by
      rw [mem_singleton] at hx hy ⊢
      exact le_antisymm (hy ▸ hzy) (hx ▸ hxz)⟩, Nat.one_pos, by simp⟩
  exact d.elim0

/-- The interval type on three points is not legal. -/
private theorem not_isLegal_interval_three : ¬ (interval 3).IsLegal :=
  not_isLegal_interval (by decide)

/-- The increasing enumeration of `{0, 1, 2}` in `Fin 4`. -/
private def lower : Fin 3 ↪ Fin 4 := ⟨![0, 1, 2], by decide⟩

/-- The points `{0, 1, 2}` form an interval of `Fin 4`, a closed face of `interval 4`. -/
private theorem map_lower_mem_faces : univ.map lower ∈ (interval 4).toCellScheme.faces := by
  decide

/-- The whole chart of `interval 4`, as an occurrence of its face realization. -/
private noncomputable def whole : (interval 4).faceRealization.Occurrence :=
  ⟨4, Function.Embedding.refl _, interval 4, StageType.restrictFace_refl (interval 4)⟩

/-- **Two distinct charts containing the same pair in an exactly consistent covering
realization**: in the face realization of `interval 4`, the whole chart and its face on
`{0, 1, 2}` have different supports, both contain `0` and `1`, and compute the same hull of
`{0, 1}`. -/
private example : ∃ x y : (interval 4).faceRealization.Occurrence, x.support ≠ y.support ∧
    ({0, 1} : Finset (Fin 4)) ⊆ x.support ∧ ({0, 1} : Finset (Fin 4)) ⊆ y.support ∧
      x.hull {0, 1} = y.hull {0, 1} := by
  let y := whole.face StageType.isConsistent_faceRealization lower map_lower_mem_faces
  have hx : ({0, 1} : Finset (Fin 4)) ⊆ whole.support := by decide
  have hy : ({0, 1} : Finset (Fin 4)) ⊆ y.support := by decide
  exact ⟨whole, y, by decide, hx, hy, whole.hull_eq_hull StageType.isConsistent_faceRealization
    StageType.isCovering_faceRealization hx hy⟩

/-! ### Exact consistency cannot be dropped -/

/-- The interval type on three points is generated by its end points. -/
private theorem hull_interval_three :
    Geometry.hull univ (interval 3).toCellScheme.faces {0, 2} = univ := by
  decide

open Classical in
/-- The realization on `Fin 4` in which the increasing enumerations of `{0, 1, 3}`, of
`{0, 2, 3}`, and of all four points have the interval types, and no other tuple has a type. -/
private noncomputable def twoIntervals : Realization.{0, 0} 0 (Fin 4) where
  eval {n} t := if StrictMono t ∧
      (univ.map t = {0, 1, 3} ∨ univ.map t = {0, 2, 3} ∨ univ.map t = univ) then
    some (interval n) else none

open Classical in
/-- The evaluation of `twoIntervals`. -/
private theorem twoIntervals_eval {n : ℕ} (t : Fin n ↪ Fin 4) :
    twoIntervals.eval t = if StrictMono t ∧
      (univ.map t = {0, 1, 3} ∨ univ.map t = {0, 2, 3} ∨ univ.map t = univ) then
        some (interval n) else none :=
  rfl

/-- The increasing enumeration of `{0, 1, 3}`. -/
private def first : Fin 3 ↪ Fin 4 := ⟨![0, 1, 3], by decide⟩

/-- The increasing enumeration of `{0, 2, 3}`. -/
private def second : Fin 3 ↪ Fin 4 := ⟨![0, 2, 3], by decide⟩

/-- `first` has the interval type on three points. -/
private theorem eval_first : twoIntervals.eval first = some (interval 3) := by
  rw [twoIntervals_eval, ite_eq_left (by decide)]

/-- `second` has the interval type on three points. -/
private theorem eval_second : twoIntervals.eval second = some (interval 3) := by
  rw [twoIntervals_eval, ite_eq_left (by decide)]

/-- `twoIntervals` is covering: every tuple is a face of the enumeration of all four points. -/
private theorem isCovering_twoIntervals : twoIntervals.IsCovering := fun _ t ↦
  ⟨4, Function.Embedding.refl _, t, by ext; simp, by
    rw [twoIntervals_eval, ite_eq_left ⟨strictMono_id, Or.inr (Or.inr (by simp))⟩]
    rfl⟩

/-- The two occurrences of the interval type on three points agree at its end points but differ
at its middle point. -/
private theorem first_ne_second : first ≠ second := fun h ↦
  absurd (DFunLike.congr_fun h 1) (by decide)

/-- **Exact consistency cannot be dropped from the two-charts theorem**: `twoIntervals` is
covering, but its two occurrences `first` and `second` of the interval type on three points agree
at the end points and differ, so it is not exactly consistent. -/
private theorem not_isConsistent_twoIntervals : ¬ twoIntervals.IsConsistent := fun hR ↦
  first_ne_second (eq_of_eval_eq_some hR isCovering_twoIntervals hull_interval_three eval_first
    eval_second (by decide) (by decide))

/-! ### The realization with no types -/

/-- The realization in which no tuple has a type. -/
private def untyped (α : Ordinal.{u}) (M : Type v) : Realization.{u, v} α M where
  eval _ := none

/-- The realization with no types is exactly consistent: there is no typed tuple. -/
private example : (untyped α M).IsConsistent :=
  fun _ _ _ _ _ h ↦ absurd h (Option.some_ne_none _).symm

/-- The realization with no types is not covering: the empty tuple is a face of no typed tuple. -/
private example : ¬ (untyped α M).IsCovering := fun hc ↦ by
  obtain ⟨_, _, _, _, h⟩ := hc (Function.Embedding.ofIsEmpty : Fin 0 ↪ M)
  exact Bool.false_ne_true h

/-- In the realization with no types every hull operation takes its default value. -/
private example (ι : HullIndex.{u} α) (a b : M) : (untyped α M).hullOp ι a b = a :=
  hullOp_of_not_exists fun ⟨_, h, _⟩ ↦ absurd h (Option.some_ne_none _).symm

/-! ### An empty carrier -/

/-- The face realization of a stage type on no points is an exactly consistent covering
realization on an empty carrier, and the empty tuple is an occurrence. -/
private example (P : StageType.{u} α 0) :
    IsEmpty (Fin 0) ∧ P.faceRealization.IsConsistent ∧ P.faceRealization.IsCovering ∧
      P.faceRealization.eval (Function.Embedding.refl (Fin 0)) = some P :=
  ⟨inferInstance, StageType.isConsistent_faceRealization, StageType.isCovering_faceRealization,
    StageType.restrictFace_refl P⟩

/-! ### Repeated inputs -/

/-- There is no chart witness at a repeated pair: the generators of a hull index are distinct. -/
private theorem not_exists_chartWitness_self {R : Realization.{u, v} α M} (ι : HullIndex.{u} α)
    (a : M) : ¬ ∃ g : Fin ι.arity ↪ M, R.eval g = some ι.type ∧ g ι.left = a ∧ g ι.right = a :=
  fun ⟨g, _, hl, hr⟩ ↦ ι.left_ne_right (g.injective (hl.trans hr.symm))

/-- At a repeated pair, the default value is the only solution of the defining relation. -/
private example {R : Realization.{u, v} α M} (hR : R.IsConsistent) (hc : R.IsCovering)
    (ι : HullIndex.{u} α) (a y : M) : R.hullOp ι a a = y ↔ y = a := by
  rw [hullOp_eq_iff hR hc]
  refine ⟨?_, fun h ↦ Or.inr ⟨not_exists_chartWitness_self ι a, h⟩⟩
  rintro (⟨g, hg, hl, hr, -⟩ | ⟨-, h⟩)
  exacts [absurd ⟨g, hg, hl, hr⟩ (not_exists_chartWitness_self ι a), h]

/-- Embeddings preserve the default value at a repeated pair. -/
private example {R : Realization.{u, v} α M} {S : Realization.{u, w} α N} (hR : R.IsConsistent)
    (hcR : R.IsCovering) (hS : S.IsConsistent) (hcS : S.IsCovering) (φ : R.Embedding S)
    (ι : HullIndex.{u} α) (a : M) : S.hullOp ι (φ a) (φ a) = φ (R.hullOp ι a a) :=
  φ.hullOp_map hR hcR hS hcS ι a a

/-- The two generators may coincide: a stage type on one point is generated by its point twice,
and two occurrences of it with the same point are equal. -/
private example {R : Realization.{u, v} α M} (hR : R.IsConsistent) (hc : R.IsCovering)
    {q : StageType.{u} α 1} {g g' : Fin 1 ↪ M} (hg : R.eval g = some q)
    (hg' : R.eval g' = some q) (h : g 0 = g' 0) : g = g' := by
  have hgen : Geometry.hull univ q.toCellScheme.faces {0, 0} = univ :=
    eq_univ_of_forall fun j ↦ by
      rw [Subsingleton.elim j 0]
      exact Geometry.subset_hull (subset_univ _) (mem_insert_self 0 _)
  exact eq_of_eval_eq_some hR hc hgen hg hg' h h

end VaughtConjecture.Realization
